package com.energyict.smartmeterprotocolimpl.elster.apollo;

import com.energyict.dlms.UniversalObject;
import com.energyict.dlms.cosem.DLMSClassId;
import com.energyict.obis.ObisCode;

/**
 * Copyrights EnergyICT
 * Date: 22/07/11
 * Time: 17:09
 */
public class AS300ObjectList {

    public static final UniversalObject[] OBJECT_LIST;

    static {
        OBJECT_LIST = new UniversalObject[]{
                new UniversalObject(ObisCode.fromString("0.0.41.0.0.255"), DLMSClassId.SAP_ASSIGNMENT),
                new UniversalObject(ObisCode.fromString("0.0.40.0.1.255"), DLMSClassId.ASSOCIATION_LN),
                new UniversalObject(ObisCode.fromString("0.0.40.0.2.255"), DLMSClassId.ASSOCIATION_LN),
                new UniversalObject(ObisCode.fromString("0.0.40.0.3.255"), DLMSClassId.ASSOCIATION_LN),
                new UniversalObject(ObisCode.fromString("0.0.40.0.4.255"), DLMSClassId.ASSOCIATION_LN),
                new UniversalObject(ObisCode.fromString("0.0.40.0.5.255"), DLMSClassId.ASSOCIATION_LN),
                new UniversalObject(ObisCode.fromString("0.0.40.0.0.255"), DLMSClassId.ASSOCIATION_LN),
                new UniversalObject(ObisCode.fromString("0.0.43.0.1.255"), DLMSClassId.SECURITY_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.43.0.2.255"), DLMSClassId.SECURITY_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.43.0.3.255"), DLMSClassId.SECURITY_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.43.0.4.255"), DLMSClassId.SECURITY_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.43.0.5.255"), DLMSClassId.SECURITY_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.43.0.0.255"), DLMSClassId.SECURITY_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.42.0.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.3.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.4.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.5.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.6.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.7.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.8.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.9.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.10.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.50.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.1.51.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.0.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.1.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.2.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.3.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.4.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.5.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.6.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.7.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.8.0.2.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.0.0.2.8.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.1.0.0.255"), DLMSClassId.CLOCK),
                new UniversalObject(ObisCode.fromString("1.0.0.9.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.0.0.9.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.0.0.9.11.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.0.9.9.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.13.0.1.255"), DLMSClassId.ACTIVITY_CALENDAR),
                new UniversalObject(ObisCode.fromString("0.0.10.0.100.255"), DLMSClassId.SCRIPT_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.10.1.100.255"), DLMSClassId.SCRIPT_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.14.0.7.255"), DLMSClassId.REGISTER_ACTIVATION),
                new UniversalObject(ObisCode.fromString("0.0.93.44.10.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.93.44.11.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.11.0.0.255"), DLMSClassId.SPECIAL_DAYS_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.96.14.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.15.0.1.255"), DLMSClassId.SINGLE_ACTION_SCHEDULE),
                new UniversalObject(ObisCode.fromString("0.0.10.0.106.255"), DLMSClassId.SCRIPT_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.96.3.10.255"), DLMSClassId.DISCONNECT_CONTROL),
                new UniversalObject(ObisCode.fromString("0.0.15.0.3.255"), DLMSClassId.SINGLE_ACTION_SCHEDULE),
                new UniversalObject(ObisCode.fromString("0.0.10.0.103.255"), DLMSClassId.SCRIPT_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.31.128.0.255"), DLMSClassId.REGISTER_MONITOR),
                new UniversalObject(ObisCode.fromString("0.0.97.97.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.97.98.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.97.98.10.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.98.0.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.98.1.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.98.2.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.3.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.98.3.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.3.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.3.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.4.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.98.4.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.4.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.4.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.5.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.97.5.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.5.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.5.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.6.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.97.6.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.6.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.6.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.7.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.97.7.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.7.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.7.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.13.0.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.13.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.97.20.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.99.97.21.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.96.13.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.13.3.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.97.22.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.99.97.23.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.1.96.3.10.255"), DLMSClassId.DISCONNECT_CONTROL),
                new UniversalObject(ObisCode.fromString("1.0.5.8.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.6.8.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.7.8.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.8.8.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.1.4.0.255"), DLMSClassId.DEMAND_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.2.4.0.255"), DLMSClassId.DEMAND_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.3.4.0.255"), DLMSClassId.DEMAND_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.4.4.0.255"), DLMSClassId.DEMAND_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.9.4.0.255"), DLMSClassId.DEMAND_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.10.4.0.255"), DLMSClassId.DEMAND_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.2.6.0.255"), DLMSClassId.EXTENDED_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.3.6.0.255"), DLMSClassId.EXTENDED_REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.4.6.0.255"), DLMSClassId.EXTENDED_REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.10.0.1.255"), DLMSClassId.SCRIPT_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.15.0.0.255"), DLMSClassId.SINGLE_ACTION_SCHEDULE),
                new UniversalObject(ObisCode.fromString("0.0.98.1.0.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.98.1.1.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("1.0.0.9.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.99.2.0.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.99.2.1.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.96.10.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("1.0.99.1.0.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.96.10.2.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.22.0.0.255"), DLMSClassId.IEC_HDLC_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.22.0.1.255"), DLMSClassId.IEC_HDLC_SETUP),
                new UniversalObject(ObisCode.fromString("0.0.44.0.0.255"), DLMSClassId.IMAGE_TRANSFER),
                new UniversalObject(ObisCode.fromString("0.0.15.0.2.255"), DLMSClassId.SINGLE_ACTION_SCHEDULE),
                new UniversalObject(ObisCode.fromString("0.0.10.0.107.255"), DLMSClassId.SCRIPT_TABLE),
                new UniversalObject(ObisCode.fromString("0.0.96.7.21.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.96.7.9.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.96.7.20.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.96.7.19.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.32.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.31.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.15.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.1.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.2.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.130.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.9.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.13.7.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.24.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.32.24.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.31.24.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.0.8.2.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.11.35.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.11.44.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.11.36.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.35.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.44.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.36.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.31.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.43.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.14.32.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.13.31.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.13.43.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("1.0.13.32.0.255"), DLMSClassId.REGISTER),
                new UniversalObject(ObisCode.fromString("0.0.96.60.1.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.11.9.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.99.98.9.255"), DLMSClassId.PROFILE_GENERIC),
                new UniversalObject(ObisCode.fromString("0.0.93.44.9.255"), DLMSClassId.DATA),
                new UniversalObject(ObisCode.fromString("0.0.96.15.9.255"), DLMSClassId.DATA),
        };
    }

}
