package com.elster.jupiter.cbo;

public enum QualityCodeCategory {
	VALID,
	DIAGNOSTICS,
	POWERQUALITY,
	TAMPER,
	DATACOLLECTION,
	REASONABILITY,
	VALIDATION,
	EDITED,
	ESTIMATED,
	OBSOLETE_OSCILLATORY,
	QUESTIONABLE,
	DERIVED,
	PROJECTED;
}
