
/*
 * Copyright (c) 2017 by Honeywell International Inc. All Rights Reserved
 */

/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src",
  "Ext.Msg": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/window/MessageBox.js",
  "Uni": "../../src"
});
Ext.ClassManager.addNameAlternateMappings({
  "Uni.About": [],
  "Uni.Loader": [],
  "Uni.controller.Configuration": [],
  "Uni.controller.Error": [],
  "Uni.controller.Navigation": [],
  "Uni.controller.Notifications": [],
  "Uni.controller.Search": [],
  "Uni.controller.history.Converter": [],
  "Uni.controller.history.EventBus": [],
  "Uni.controller.history.Settings": [],
  "Uni.model.AppItem": [],
  "Uni.model.BreadcrumbItem": [],
  "Uni.model.MenuItem": [],
  "Uni.model.Notification": [],
  "Uni.model.Translation": [],
  "Uni.override.ApplicationOverride": [],
  "Uni.override.CheckboxOverride": [],
  "Uni.override.FieldBaseOverride": [],
  "Uni.override.FieldContainerOverride": [],
  "Uni.override.JsonWriterOverride": [],
  "Uni.override.LabelableOverride": [],
  "Uni.override.NumberFieldOverride": [],
  "Uni.override.RestOverride": [],
  "Uni.override.StoreOverride": [],
  "Uni.store.AppItems": [],
  "Uni.store.MenuItems": [],
  "Uni.store.Notifications": [],
  "Uni.store.Translations": [],
  "Uni.util.History": [],
  "Uni.util.I18n": [],
  "Uni.util.QueryString": [],
  "Uni.view.Viewport": [],
  "Uni.view.breadcrumb.Link": [],
  "Uni.view.breadcrumb.Separator": [],
  "Uni.view.breadcrumb.Trail": [],
  "Uni.view.container.ContentContainer": [],
  "Uni.view.error.Window": [],
  "Uni.view.form.field.Vtypes": [],
  "Uni.view.navigation.AppSwitcher": [],
  "Uni.view.navigation.Footer": [],
  "Uni.view.navigation.Header": [],
  "Uni.view.navigation.Help": [],
  "Uni.view.navigation.Logo": [],
  "Uni.view.navigation.Menu": [],
  "Uni.view.navigation.SubMenu": [],
  "Uni.view.notifications.Anchor": [],
  "Uni.view.search.Basic": [],
  "Uni.view.search.Quick": [],
  "Uni.view.toolbar.PagingBottom": [],
  "Uni.view.toolbar.PagingTop": [],
  "Uni.view.user.Menu": [],
  "Uni.view.window.Wizard": []
});
Ext.ClassManager.addNameAliasMappings({
  "Uni.About": [],
  "Uni.Loader": [],
  "Uni.controller.Configuration": [],
  "Uni.controller.Error": [],
  "Uni.controller.Navigation": [],
  "Uni.controller.Notifications": [],
  "Uni.controller.Search": [],
  "Uni.controller.history.Converter": [],
  "Uni.controller.history.EventBus": [],
  "Uni.controller.history.Settings": [],
  "Uni.model.AppItem": [],
  "Uni.model.BreadcrumbItem": [],
  "Uni.model.MenuItem": [],
  "Uni.model.Notification": [],
  "Uni.model.Translation": [],
  "Uni.override.ApplicationOverride": [],
  "Uni.override.CheckboxOverride": [],
  "Uni.override.FieldBaseOverride": [],
  "Uni.override.FieldContainerOverride": [],
  "Uni.override.JsonWriterOverride": [],
  "Uni.override.LabelableOverride": [],
  "Uni.override.NumberFieldOverride": [],
  "Uni.override.RestOverride": [],
  "Uni.override.StoreOverride": [],
  "Uni.store.AppItems": [],
  "Uni.store.MenuItems": [],
  "Uni.store.Notifications": [],
  "Uni.store.Translations": [],
  "Uni.util.History": [],
  "Uni.util.I18n": [],
  "Uni.util.QueryString": [],
  "Uni.view.Viewport": [],
  "Uni.view.breadcrumb.Link": [
    "widget.breadcrumbLink"
  ],
  "Uni.view.breadcrumb.Separator": [
    "widget.breadcrumbSeparator"
  ],
  "Uni.view.breadcrumb.Trail": [
    "widget.breadcrumbTrail"
  ],
  "Uni.view.container.ContentContainer": [
    "widget.contentcontainer"
  ],
  "Uni.view.error.Window": [
    "widget.errorWindow"
  ],
  "Uni.view.form.field.Vtypes": [],
  "Uni.view.navigation.AppSwitcher": [
    "widget.navigationAppSwitcher"
  ],
  "Uni.view.navigation.Footer": [
    "widget.navigationFooter"
  ],
  "Uni.view.navigation.Header": [
    "widget.navigationHeader"
  ],
  "Uni.view.navigation.Help": [
    "widget.navigationHelp"
  ],
  "Uni.view.navigation.Logo": [
    "widget.navigationLogo"
  ],
  "Uni.view.navigation.Menu": [
    "widget.navigationMenu"
  ],
  "Uni.view.navigation.SubMenu": [
    "widget.navigationSubMenu"
  ],
  "Uni.view.notifications.Anchor": [
    "widget.notificationsAnchor"
  ],
  "Uni.view.search.Basic": [
    "widget.searchBasic"
  ],
  "Uni.view.search.Quick": [
    "widget.searchQuick"
  ],
  "Uni.view.toolbar.PagingBottom": [
    "widget.pagingtoolbarbottom"
  ],
  "Uni.view.toolbar.PagingTop": [
    "widget.pagingtoolbartop"
  ],
  "Uni.view.user.Menu": [
    "widget.userMenu"
  ],
  "Uni.view.window.Wizard": []
});
