Ext.define('Dxp.store.Logs', {
    extend: 'Ext.data.Store',
    model: 'Dxp.model.Log',
    pageSize: 50,
    data: [
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported'},
        {timestamp: '2013 Oct 01 11:24:06 AM', logLevel: 'Error', message: 'Exception 1653'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 09:35:07 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'},
        {timestamp: '2013 Oct 01 00:08:00 PM', logLevel: 'Warning', message: 'Device X and reading type(s) do not contain data for the selected export period.'},
        {timestamp: '2013 Oct 01 02:29:33 PM', logLevel: 'Warning', message: 'Some devices of device group A do not contain the selected reading type(s) that have to be exported.'}
    ]
});
