<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2017 by Honeywell International Inc. All Rights Reserved
  -->

<wsdl:definitions
        name="GetEndDeviceEvents"
        targetNamespace="http://iec.ch/TC57/2011/GetEndDeviceEvents"
        xmlns:tns="http://iec.ch/TC57/2011/GetEndDeviceEvents"
        xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:infoMessage="http://iec.ch/TC57/2011/GetEndDeviceEventsMessage">
    <wsdl:types>
        <xs:schema
                targetNamespace="http://iec.ch/TC57/2011/GetEndDeviceEvents"
                elementFormDefault="qualified">
            <xs:import
                    namespace="http://iec.ch/TC57/2011/GetEndDeviceEventsMessage"
                    schemaLocation="xsd/GetEndDeviceEventsMessage.xsd"/>
        </xs:schema>
    </wsdl:types>
    <!-- Message Definitions -->
    <wsdl:message name="GetEndDeviceEventsRequestMessage">
        <wsdl:part name="GetEndDeviceEventsRequestMessage"
                   element="infoMessage:GetEndDeviceEvents"/>
    </wsdl:message>
    <wsdl:message name="ResponseMessage">
        <wsdl:part name="ResponseMessage"
                   element="infoMessage:EndDeviceEventsResponseMessage"/>
    </wsdl:message>
    <wsdl:message name="FaultMessage">
        <wsdl:part name="FaultMessage"
                   element="infoMessage:EndDeviceEventsFaultMessage"/>
    </wsdl:message>
    <!-- Port Definitions -->
    <wsdl:portType name="GetEndDeviceEvents_Port">
        <wsdl:operation name="GetEndDeviceEvents">
            <wsdl:input name="GetEndDeviceEventsRequest"
                        message="tns:GetEndDeviceEventsRequestMessage"/>
            <wsdl:output name="GetEndDeviceEventsResponse"
                         message="tns:ResponseMessage"/>
            <wsdl:fault name="GetEndDeviceEventsFault"
                        message="tns:FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetEndDeviceEvents_Binding"
                  type="tns:GetEndDeviceEvents_Port">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetEndDeviceEvents">
            <soap:operation
                    soapAction="http://iec.ch/TC57/2011/GetEndDeviceEvents/GetEndDeviceEvents" style="document"/>
            <wsdl:input name="GetEndDeviceEventsRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetEndDeviceEventsResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="GetEndDeviceEventsFault">
                <soap:fault name="GetEndDeviceEventsFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="GetEndDeviceEvents">
        <wsdl:port name="GetEndDeviceEvents_Port"
                   binding="tns:GetEndDeviceEvents_Binding">
            <soap:address
                    location="http://iec.ch/TC57/2011/GetEndDeviceEvents/GetEndDeviceEvents"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>