<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2017 by Honeywell International Inc. All Rights Reserved
  -->

<wsdl:definitions
        name="SendMeterConfig"
        targetNamespace="http://iec.ch/TC57/2011/SendMeterConfig"
        xmlns:tns="http://iec.ch/TC57/2011/SendMeterConfig"
        xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:infoMessage1="http://iec.ch/TC57/2011/GetMeterConfigMessage"
        xmlns:infoMessage2="http://iec.ch/TC57/2011/MeterConfigMessage">
    <wsdl:types>
        <xs:schema targetNamespace="http://iec.ch/TC57/2011/SendMeterConfig"
                   elementFormDefault="qualified">
            <xs:import
                    namespace="http://iec.ch/TC57/2011/MeterConfigMessage"
                    schemaLocation="xsd/MeterConfigMessage.xsd"/>
            <xs:import
                    namespace="http://iec.ch/TC57/2011/GetMeterConfigMessage"
                    schemaLocation="xsd/GetMeterConfigMessage.xsd"/>
        </xs:schema>
    </wsdl:types>
    <!-- Message Definitions -->
    <wsdl:message name="SendMeterConfigEventMessage">
        <wsdl:part name="SendMeterConfigEventMessage"
                   element="infoMessage1:GetMeterConfigEventMessage"/>
    </wsdl:message>
    <wsdl:message name="ResponseMessage">
        <wsdl:part name="ResponseMessage"
                   element="infoMessage2:MeterConfigResponseMessage"/>
    </wsdl:message>
    <wsdl:message name="FaultMessage">
        <wsdl:part name="FaultMessage"
                   element="infoMessage2:MeterConfigFaultMessage"/>
    </wsdl:message>
    <!-- Port Definitions -->
    <wsdl:portType name="MeterConfig_Port">
        <wsdl:operation name="SendMeterConfig">
            <wsdl:input name="SendMeterConfigEvent"
                        message="tns:SendMeterConfigEventMessage"/>
            <wsdl:output name="SendMeterConfigResponse"
                         message="tns:ResponseMessage"/>
            <wsdl:fault name="SendMeterConfigFault"
                        message="tns:FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MeterConfig_Binding"
                  type="tns:MeterConfig_Port">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SendMeterConfig">
            <soap:operation
                    soapAction="http://iec.ch/TC57/2011/MeterConfig/SendMeterConfig" style="document"/>
            <wsdl:input name="SendMeterConfigEvent">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="SendMeterConfigResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="SendMeterConfigFault">
                <soap:fault name="SendMeterConfigFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SendMeterConfig">
        <wsdl:port name="MeterConfig_Port"
                   binding="tns:MeterConfig_Binding">
            <soap:address location="http://iec.ch/TC57/2011/SendMeterConfig"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>