/*
 * Copyright (c) 2016 by Honeywell International Inc. All Rights Reserved
 */

package com.energyict.cim;

import java.util.Objects;

/**
 * Enum containing the mapping between the meter protocol event code and the corresponding CIM {@link EndDeviceEventType}.
 *
 * @author sva
 * @since 3/06/13 - 15:00
 */
public enum EndDeviceEventTypeMapping {

    OTHER                   (0, EndDeviceEventTypeFactory.getOtherEventType()),
    POWERDOWN               (1, EndDeviceEventTypeFactory.getPowerDownEventType()),
    POWERUP                 (2, EndDeviceEventTypeFactory.getPowerUpEventType()),
    WATCHDOGRESET           (3, EndDeviceEventTypeFactory.getWatchdogResetEventType()),
    SETCLOCK_BEFORE         (4, EndDeviceEventTypeFactory.getSetClockBeforeEventType()),
    SETCLOCK_AFTER          (5, EndDeviceEventTypeFactory.getSetClockAfterEventType()),
    SETCLOCK                (6, EndDeviceEventTypeFactory.getSetClockEventType()),
    CONFIGURATIONCHANGE     (7, EndDeviceEventTypeFactory.getConfigurationChangeEventType()),
    RAM_MEMORY_ERROR        (8, EndDeviceEventTypeFactory.getRamMemoryErrorEventType()),
    PROGRAM_FLOW_ERROR      (9, EndDeviceEventTypeFactory.getProgramFlowErrorEventType()),
    REGISTER_OVERFLOW       (10, EndDeviceEventTypeFactory.getRegisterOverflowEventType()),
    FATAL_ERROR             (11, EndDeviceEventTypeFactory.getFatalErrorEventType()),
    CLEAR_DATA              (12, EndDeviceEventTypeFactory.getClearDataEventType()),
    HARDWARE_ERROR          (13, EndDeviceEventTypeFactory.getHardwareErrorEventType()),
    METER_ALARM             (14, EndDeviceEventTypeFactory.getMeterAlarmEventType()),
    ROM_MEMORY_ERROR        (15, EndDeviceEventTypeFactory.getRomMemoryErrorEventType()),
    MAXIMUM_DEMAND_RESET    (16, EndDeviceEventTypeFactory.getMaximumDemandResetEventType()),
    BILLING_ACTION          (17, EndDeviceEventTypeFactory.getBillingActionEventType()),
    APPLICATION_ALERT_START (18, EndDeviceEventTypeFactory.getApplicationAlertStartEventType()),
    APPLICATION_ALERT_STOP  (19, EndDeviceEventTypeFactory.getApplicationAlertStopEventType()),
    PHASE_FAILURE           (20, EndDeviceEventTypeFactory.getPhaseFailureEventType()),
    VOLTAGE_SAG             (21, EndDeviceEventTypeFactory.getVoltageSagEventType()),
    VOLTAGE_SWELL           (22, EndDeviceEventTypeFactory.getVoltageSwellEventType()),
    TAMPER                  (23, EndDeviceEventTypeFactory.getTamperEventType()),
    COVER_OPENED            (24, EndDeviceEventTypeFactory.getCoverOpenedEventType()),
    TERMINAL_OPENED         (25, EndDeviceEventTypeFactory.getTamperCase()),
    REVERSE_RUN             (26, EndDeviceEventTypeFactory.getReverseRunEventType()),
    LOADPROFILE_CLEARED     (27, EndDeviceEventTypeFactory.getLoadProfileClearedEventType()),
    EVENT_LOG_CLEARED       (28, EndDeviceEventTypeFactory.getEventLogClearedEventType()),
    DAYLIGHT_SAVING_TIME_ENABLED_OR_DISABLED(29,EndDeviceEventTypeFactory.getDaylightSavingTimeEnabledOrDisabledEventType()),
    CLOCK_INVALID           (30, EndDeviceEventTypeFactory.getClockInvalidEventType()),
    REPLACE_BATTERY         (31, EndDeviceEventTypeFactory.getReplaceBatteryEventType()),
    BATTERY_VOLTAGE_LOW     (32, EndDeviceEventTypeFactory.getBatteryVoltageLowEventType()),
    TOU_ACTIVATED           (33, EndDeviceEventTypeFactory.getTouActivatedEventType()),
    ERROR_REGISTER_CLEARED  (34, EndDeviceEventTypeFactory.getErrorRegisterClearedEventType()),
    ALARM_REGISTER_CLEARED  (35, EndDeviceEventTypeFactory.getAlarmRegisterClearedEventType()),
    PROGRAM_MEMORY_ERROR    (36, EndDeviceEventTypeFactory.getProgramMemoryErrorEventType()),
    NV_MEMORY_ERROR         (37, EndDeviceEventTypeFactory.getNvMemoryErrorEventType()),
    WATCHDOG_ERROR          (38, EndDeviceEventTypeFactory.getWatchdogErrorEventType()),
    MEASUREMENT_SYSTEM_ERROR(39, EndDeviceEventTypeFactory.getMeasurementSystemErrorEventType()),
    FIRMWARE_READY_FOR_ACTIVATION(40, EndDeviceEventTypeFactory.getFirmwareReadyForActivationEventType()),
    FIRMWARE_ACTIVATED      (41, EndDeviceEventTypeFactory.getFirmwareActivatedEventType()),
    TERMINAL_COVER_CLOSED   (42, EndDeviceEventTypeFactory.getTerminalCoverClosedEventType()),
    STRONG_DC_FIELD_DETECTED(43, EndDeviceEventTypeFactory.getStrongDCFieldDetectedEventType()),
    NO_STRONG_DC_FIELD_ANYMORE(44, EndDeviceEventTypeFactory.getNoStrongDCFieldAnymoreEventType()),
    METER_COVER_CLOSED      (45, EndDeviceEventTypeFactory.getMeterCoverClosedEventType()),
    N_TIMES_WRONG_PASSWORD  (46, EndDeviceEventTypeFactory.getNTimesWrongPasswordEventType()),
    MANUAL_DISCONNECTION    (47, EndDeviceEventTypeFactory.getManualDisconnectionEventType()),
    MANUAL_CONNECTION       (48, EndDeviceEventTypeFactory.getManualConnectionEventType()),
    REMOTE_DISCONNECTION    (49, EndDeviceEventTypeFactory.getRemoteDisconnectionEventType()),
    REMOTE_CONNECTION       (50, EndDeviceEventTypeFactory.getRemoteConnectionEventType()),
    LOCAL_DISCONNECTION     (51, EndDeviceEventTypeFactory.getLocalDisconnectionEventType()),
    LIMITER_THRESHOLD_EXCEEDED(52, EndDeviceEventTypeFactory.getLimiterThresholdExceededEventType()),
    LIMITER_THRESHOLD_OK    (53, EndDeviceEventTypeFactory.getLimiterThresholdOkEventType()),
    LIMITER_THRESHOLD_CHANGED(54, EndDeviceEventTypeFactory.getLimiterThresholdChangedEventType()),
    COMMUNICATION_ERROR_MBUS(55, EndDeviceEventTypeFactory.getCommunicationErrorMbusEventType()),
    COMMUNICATION_OK_MBUS   (56, EndDeviceEventTypeFactory.getCommunicationOkMbusEventType()),
    REPLACE_BATTERY_MBUS    (57, EndDeviceEventTypeFactory.getReplaceBatteryMbusEventType()),
    FRAUD_ATTEMPT_MBUS      (58, EndDeviceEventTypeFactory.getFraudAttemptMbusEventType()),
    CLOCK_ADJUSTED_MBUS     (59, EndDeviceEventTypeFactory.getClockAdjustedMbusEventType()),
    MANUAL_DISCONNECTION_MBUS(60, EndDeviceEventTypeFactory.getManualDisconnectionMbusEventType()),
    MANUAL_CONNECTION_MBUS  (61, EndDeviceEventTypeFactory.getManualConnectionMbusEventType()),
    REMOTE_DISCONNECTION_MBUS(62, EndDeviceEventTypeFactory.getRemoteDisconnectionMbusEventType()),
    REMOTE_CONNECTION_MBUS  (63, EndDeviceEventTypeFactory.getRemoteConnectionMbusEventType()),
    VALVE_ALARM_MBUS        (64, EndDeviceEventTypeFactory.getValveAlarmMbusEventType()),
    TAMPER_CLEARED          (65, EndDeviceEventTypeFactory.getTamperClearedEventType()),

    //DSMR - ESMR Communication events
    EVENT_METROLOGICAL_MAINTENANCE  (71, EndDeviceEventTypeFactory.getMetrologicalMaintenanceEventType()),
    EVENT_TECHNICAL_MAINTENANCE     (72, EndDeviceEventTypeFactory.getTechnicalMaintenanceEventType()),
    EVENT_RETRIEVE_METER_READINGS_E (73, EndDeviceEventTypeFactory.getRetrieveEmeterReadingsElectricityEventType()),
    EVENT_RETRIEVE_METER_READINGS_G (74, EndDeviceEventTypeFactory.getRetrieveEmeterReadingsGasEventType()),
    EVENT_RETRIEVE_INTERVAL_DATA_E  (75, EndDeviceEventTypeFactory.getRetrieveEmeterIntervalElectricityEventType()),
    EVENT_RETRIEVE_INTERVAL_DATA_G  (76, EndDeviceEventTypeFactory.getRetrieveEmeterIntervalGasEventType()),

    //DSMR - ESMR Power Voltage
    EVENT_SHORT_VOLTAGE_SAG_L1      (77, EndDeviceEventTypeFactory.getShortVoltageSagL1EventType()),
    EVENT_SHORT_VOLTAGE_SAG_L2      (78, EndDeviceEventTypeFactory.getShortVoltageSagL2EventType()),
    EVENT_SHORT_VOLTAGE_SAG_L3      (79, EndDeviceEventTypeFactory.getShortVoltageSagL3EventType()),

    EVENT_EVENT_LOG_CLEARED         (255, EndDeviceEventTypeFactory.getClearedEventType()),

    SAG_PHASE_A             (80, EndDeviceEventTypeFactory.getSagEventPhaseA()),
    SAG_PHASE_B             (81, EndDeviceEventTypeFactory.getSagEventPhaseB()),
    SAG_PHASE_C             (82, EndDeviceEventTypeFactory.getSagEventPhaseC()),
    SAG_PHASE_A_B           (83, EndDeviceEventTypeFactory.getSagEventPhaseAB()),
    SAG_PHASE_B_C           (84, EndDeviceEventTypeFactory.getSagEventPhaseBC()),
    SAG_PHASE_A_C           (85, EndDeviceEventTypeFactory.getSagEventPhaseAC()),
    SAG_PHASE_A_B_C         (86, EndDeviceEventTypeFactory.getSagEventPhaseABC()),
    SAG_EVENT_CLEARED       (87, EndDeviceEventTypeFactory.getSagEventCleared()),
    ACCESS_READ             (88, EndDeviceEventTypeFactory.getDeviceAccessedRead()),
    ACCESS_WRITE            (89, EndDeviceEventTypeFactory.getDeviceAccessedWrite()),
    PROCEDURE_INVOKED       (90, EndDeviceEventTypeFactory.getProcedureInvoked()),
    TABLE_WRITTEN           (91, EndDeviceEventTypeFactory.getTableWritten()),
    COMM_TERMINATED_NORMAL  (92, EndDeviceEventTypeFactory.getCommunicationTerminatedNormally()),
    COMM_TERMINATED_ABNORMAL(93, EndDeviceEventTypeFactory.getCommunicationTerminatedAbnormally()),
    RESET_LIST_POINTER      (94, EndDeviceEventTypeFactory.getResetListPointers()),
    UPDATE_LIST_POINTER     (95, EndDeviceEventTypeFactory.getUpdateListPointers()),
    HISTORY_LOG_CLEARED     (96, EndDeviceEventTypeFactory.getHistoryLogCleared()),
    HISTORY_LOG_POINTER     (97, EndDeviceEventTypeFactory.getHistoryLogPointer()),
    EVENT_LOG_POINTER       (98, EndDeviceEventTypeFactory.getEventLogPointer()),
    SELF_READ               (99, EndDeviceEventTypeFactory.getSelfRead()),
    DAYLIGHT_SAVING_TIME_ON (100, EndDeviceEventTypeFactory.getDaylightSavingTimeOn()),
    DAYLIGHT_SAVING_TIME_OFF(101, EndDeviceEventTypeFactory.getDaylightSavingTimeOff()),
    SEASON_CHANGE           (102, EndDeviceEventTypeFactory.getSeasonChange()),
    RATE_CHANGE             (103, EndDeviceEventTypeFactory.getRateChange()),
    SPECIAL_SCHEDULE        (104, EndDeviceEventTypeFactory.getSpecialSchedule()),
    TIER_SWITCH             (105, EndDeviceEventTypeFactory.getTierSwitch()),
    PENDING_TABLE_ACTIVATION(106, EndDeviceEventTypeFactory.getPendingTableActivation()),
    PENDING_TABLE_CLEAR     (107, EndDeviceEventTypeFactory.getPendingTableClear()),
    METERING_MODE_START     (108, EndDeviceEventTypeFactory.getMeteringModeStart()),
    METERING_MODE_STOP      (109, EndDeviceEventTypeFactory.getMeteringModeStop()),
    TEST_MODE_START         (110, EndDeviceEventTypeFactory.getTestModeStart()),
    TEST_MODE_STOP          (111, EndDeviceEventTypeFactory.getTestModeStop()),
    METER_SHOP_START        (112, EndDeviceEventTypeFactory.getMeterShopStart()),
    METER_SHOP_STOP         (113, EndDeviceEventTypeFactory.getMeterShopStop()),
    CONFIGURATION_ERROR     (114, EndDeviceEventTypeFactory.getConfigurationError()),
    SELF_CHECK_ERROR        (115, EndDeviceEventTypeFactory.getSelfCheckError()),
    RAM_FAILURE             (116, EndDeviceEventTypeFactory.getRAMFailure()),
    ROM_FAILURE             (117, EndDeviceEventTypeFactory.getROMFailure()),
    NON_VOLATILE_MEMORY_FAILURE(118, EndDeviceEventTypeFactory.getNonVolatileMemoryFailure()),
    CLOCK_ERROR             (119, EndDeviceEventTypeFactory.getClockError()),
    LOW_LOSS_POTENTIAL      (120, EndDeviceEventTypeFactory.getLowLossPotential()),
    DEMAND_OVERLOAD         (121, EndDeviceEventTypeFactory.getDemandOverload()),
    POWER_FAILURE           (122, EndDeviceEventTypeFactory.getPowerFailure()),
    REVERSE_ROTATION        (123, EndDeviceEventTypeFactory.getReverseRotation()),
    ENTER_TIER              (124, EndDeviceEventTypeFactory.getEnterExitTier()),
    EXIT_TIER               (125, EndDeviceEventTypeFactory.getEnterExitTier()),
    TERMINAL_COVER_TEMPER   (126, EndDeviceEventTypeFactory.getTamperCase()),
    MAIN_COVER_TEMPER       (127, EndDeviceEventTypeFactory.getTamperCase()),
    EXTERNAL_EVENT          (128, EndDeviceEventTypeFactory.getExternalEvent()),
    PHASE_A_OFF             (129, EndDeviceEventTypeFactory.getPhaseAOff()),
    PHASE_A_ON              (130, EndDeviceEventTypeFactory.getPhaseAOn()),
    PHASE_B_OFF             (131, EndDeviceEventTypeFactory.getPhaseBOff()),
    PHASE_B_ON              (132, EndDeviceEventTypeFactory.getPhaseBOn()),
    PHASE_C_OFF             (133, EndDeviceEventTypeFactory.getPhaseCOff()),
    PHASE_C_ON              (134, EndDeviceEventTypeFactory.getPhaseCOn()),
    RWP                     (135, EndDeviceEventTypeFactory.getRWP()),
    DEVICE_PROGRAMMED       (136, EndDeviceEventTypeFactory.getDeviceProgrammed()),
    REMOTE_FLASH_FAILURE    (137, EndDeviceEventTypeFactory.getRemoteFlashFailure()),
    SERVICE_VOLTAGE_TEST    (138, EndDeviceEventTypeFactory.getServiceVoltageTest()),
    LOW_CURRENT_TEST        (139, EndDeviceEventTypeFactory.getLowCurrentTest()),
    POWER_FACTOR            (140, EndDeviceEventTypeFactory.getPowerFactor()),
    SECOND_HARMONIC_CURRENT_TEST(141, EndDeviceEventTypeFactory.getSecondHarmonicCurrentTest()),
    TOTAL_HARMONIC_CURRENT  (142, EndDeviceEventTypeFactory.getTotalHarmonicCurrent()),
    TOTAL_HARMONIC_VOLTAGE  (143, EndDeviceEventTypeFactory.getTotalHarmonicVoltage()),
    VOLTAGE_IMBALANCE       (144, EndDeviceEventTypeFactory.getVoltageImbalance()),
    CURRENT_IMBALANCE       (145, EndDeviceEventTypeFactory.getVoltageImbalance()),
    TOTAL_DEMAND_DISTORTION (146, EndDeviceEventTypeFactory.getTotalDemandDistortion()),
    HIGH_VOLTAGE_TEST       (147, EndDeviceEventTypeFactory.getHighVoltageTest()),
    REVERSE_POWER_TEST      (148, EndDeviceEventTypeFactory.getReversePowerTest()),
    TOU_PROGRAMMED          (149, EndDeviceEventTypeFactory.getTouProgrammed()),
    EXTERNAL_ALERT          (150, EndDeviceEventTypeFactory.getExternalAlert()),
    FIRMWARE_VERIFICATION_FAIL(151, EndDeviceEventTypeFactory.getFirmwareVerificationFail()),
    UNEXPECTED_CONSUMPTION  (152, EndDeviceEventTypeFactory.getUnexpectedConsumption()),
    PHASE_REVERSAL          (153, EndDeviceEventTypeFactory.getPhaseReversal()),
    MISSING_NEUTRAL         (154, EndDeviceEventTypeFactory.getMissingNeutral()),
    N_TIMES_DECRYPT_FAIL    (155, EndDeviceEventTypeFactory.getNTimeDecryptFail()),
    DISCONNECTOR_READY_FOR_RECONN(156, EndDeviceEventTypeFactory.getDisconnectorReadyForReconn()),
    DISCONNECT_RECONNECT_FAIL(157, EndDeviceEventTypeFactory.getDisconnectReconnectFail()),
    LOCAL_RECONNECTION      (158, EndDeviceEventTypeFactory.getLocalReconnection()),
    SUPERVISION_1_EXCEEDED  (159, EndDeviceEventTypeFactory.getSupervision1Exceeded()),
    SUPERVISION_1_OK        (160, EndDeviceEventTypeFactory.getSupervision1Ok()),
    SUPERVISION_2_EXCEEDED  (161, EndDeviceEventTypeFactory.getSupervision2Exceeded()),
    SUPERVISION_2_OK        (162, EndDeviceEventTypeFactory.getSupervision2Ok()),
    SUPERVISION_3_EXCEEDED  (163, EndDeviceEventTypeFactory.getSupervision3Exceeded()),
    SUPERVISION_3_OK        (164, EndDeviceEventTypeFactory.getSupervision3Ok()),
    PHASE_ASYMMETRY         (165, EndDeviceEventTypeFactory.getPhaseAsymmetry()),
    COMMUNICATION_TIMEOUT   (166, EndDeviceEventTypeFactory.getCommunicationTimeout()),
    MODEM_INITIALIZATION_FAIL(167, EndDeviceEventTypeFactory.getModemInitializationFail()),
    SIM_CARD_FAIL           (168, EndDeviceEventTypeFactory.getSimCardFail()),
    SIM_CARD_OK             (169, EndDeviceEventTypeFactory.getSimCardOk()),
    GSM_GPRS_REGISTRATION_FAIL(170, EndDeviceEventTypeFactory.getGSM_GPRS_RegistrationFail()),
    PDP_CONTEXT_ESTABLISHED (171, EndDeviceEventTypeFactory.getPDPContextEstablished()),
    PDP_CONTEXT_DESTROYED   (172, EndDeviceEventTypeFactory.getPDPContextDestroyed()),
    PDP_CONTEXT_FAIL        (173, EndDeviceEventTypeFactory.getPDPContextFail()),
    MODEM_SW_RESET          (174, EndDeviceEventTypeFactory.getModemSWReset()),
    MODEM_HW_RESET          (175, EndDeviceEventTypeFactory.getModemHWReset()),
    GSM_CONNECTION          (176, EndDeviceEventTypeFactory.getGSMConnection()),
    GSM_HANG_UP             (177, EndDeviceEventTypeFactory.getGSMHangUp()),
    DIAGNOSTIC_FAILURE      (178, EndDeviceEventTypeFactory.getDiagnosticFailure()),
    USER_INITIALIZATION_FAIL(179, EndDeviceEventTypeFactory.getUserInitializationFail()),
    ANSWER_NUMBER_EXCEEDED  (180, EndDeviceEventTypeFactory.getAnswerNumberExceeded()),
    LOCAL_COMMUNICATION_ATTEMPT(181, EndDeviceEventTypeFactory.getLocalCommunicationAttempt()),
    GLOBAL_KEY              (182, EndDeviceEventTypeFactory.getGlobalKey()),
    UNDERVOLTAGE_L1         (183, EndDeviceEventTypeFactory.getUndervoltageL1()),
    UNDERVOLTAGE_L2         (184, EndDeviceEventTypeFactory.getUndervoltageL2()),
    UNDERVOLTAGE_L3         (185, EndDeviceEventTypeFactory.getUndervoltageL3()),
    OVERVOLTAGE_L1          (186, EndDeviceEventTypeFactory.getOvervoltageL1()),
    OVERVOLTAGE_L2          (187, EndDeviceEventTypeFactory.getOvervoltageL2()),
    OVERVOLTAGE_L3          (188, EndDeviceEventTypeFactory.getOvervoltageL3()),
    MISSINGVOLTAGE_L1       (189, EndDeviceEventTypeFactory.getMissingVoltageL1()),
    MISSINGVOLTAGE_L2       (190, EndDeviceEventTypeFactory.getMissingVoltageL2()),
    MISSINGVOLTAGE_L3       (191, EndDeviceEventTypeFactory.getMissingVoltageL3()),
    NORMALVOLTAGE_L1        (192, EndDeviceEventTypeFactory.getNormalVoltageL1()),
    NORMALVOLTAGE_L2        (193, EndDeviceEventTypeFactory.getNormalVoltageL2()),
    NORMALVOLTAGE_L3        (194, EndDeviceEventTypeFactory.getNormalVoltageL3()),
    BADVOLTAGE_L1           (195, EndDeviceEventTypeFactory.getBadVoltageL1()),
    BADVOLTAGE_L2           (196, EndDeviceEventTypeFactory.getBadVoltageL2()),
    BADVOLTAGE_L3           (197, EndDeviceEventTypeFactory.getBadVoltageL3()),
    SIGNAL_QUALITY_LOW      (198, EndDeviceEventTypeFactory.getSignalQualityLow()),
    METER_ALARM_END         (199, EndDeviceEventTypeFactory.getMeterAlarmEnd()),
    REVERSE_POWER           (200, EndDeviceEventTypeFactory.getReversePower()),
    INPUT_EVENT             (201, EndDeviceEventTypeFactory.getInputEvent()),
    CHANGE_IMPULSE          (202, EndDeviceEventTypeFactory.getChangeImpulse()),
    PLUS_A_STORED           (203, EndDeviceEventTypeFactory.getPulsAStored()),
    PARAMETER_RESTORED      (204, EndDeviceEventTypeFactory.getParameterRestored()),
    PARAMETER_INITIALIZED   (205, EndDeviceEventTypeFactory.getParameterInitialized()),
    STATUS_CHANGED          (206, EndDeviceEventTypeFactory.getStatusChanged()),
    RELAY_CONNECTED         (207, EndDeviceEventTypeFactory.getRelayConnected()),
    RELAY_DISCONNECTED      (208, EndDeviceEventTypeFactory.getRelayDisconnected()),
    RELAY_CONNECT_FAILED    (209, EndDeviceEventTypeFactory.getRelayConnectFailed()),
    RELAY_DISCONNECT_FAILED (210, EndDeviceEventTypeFactory.getRelayDisconnectFailed()),
    SESSION_STARTED         (211, EndDeviceEventTypeFactory.getSessionStarted()),
    PARAMETER_CHANGED       (212, EndDeviceEventTypeFactory.getConfigurationParameterChanged()),
    SESSION_STOPPED         (213, EndDeviceEventTypeFactory.getSessionStopped()),
    SESSION_TERMINATED      (214, EndDeviceEventTypeFactory.getSessionTerminated()),
    SESSION_EXPIRED         (215, EndDeviceEventTypeFactory.getSessionExpired()),
    SESSION_DISALLOWED      (216, EndDeviceEventTypeFactory.getSessionDisallowed()),
    SESSION_SUBSTITUTED     (217, EndDeviceEventTypeFactory.getSessionSubstituted()),
    SESSION_ABORTED         (218, EndDeviceEventTypeFactory.getSessionAborted()),
    BATTERY_STATUS_ENABLED  (219, EndDeviceEventTypeFactory.getBatteryStatusEnabled()),
    BATTERY_STATUS_DISABLED (220, EndDeviceEventTypeFactory.getBatteryStatusDisabled()),
    ASS_DEVICE_INPUT_ERROR  (221, EndDeviceEventTypeFactory.getAssociatedDeviceInputError()),
    MODEM_SESSION_FAILED    (222, EndDeviceEventTypeFactory.getModemSessionFailed()),

    LOG_RESET                               ( 223, EndDeviceEventTypeFactory.getLogReset()),
    LOCAL_COMM_START                        ( 224, EndDeviceEventTypeFactory.getLocalCommunicationStart()),
    LOCAL_COMM_END                          ( 225, EndDeviceEventTypeFactory.getLocalCommunicationEnd()),
    NOT_METRO_PARAM_CONF                    ( 226, EndDeviceEventTypeFactory.getNotMetrologicalParameterConfiguration()),
    GAS_FLOW_RATE_ABOVE_THRESHOLD_START     ( 227, EndDeviceEventTypeFactory.getGasFlowRateAboveThresholdStart()),
    GAS_FLOW_RATE_ABOVE_THRESHOLD_END       ( 228, EndDeviceEventTypeFactory.getGasFlowRateAboveThresholdEnd()),
    GAS_REVERSE_FLOW_START                  ( 229, EndDeviceEventTypeFactory.getGasReverseFlowStart()),
    GAS_REVERSE_FLOW_END                    ( 230, EndDeviceEventTypeFactory.getGasReverseFlowEnd()),
    GAS_TEMP_ABOVE_PHYSICAL_THRESHOLD_START ( 231, EndDeviceEventTypeFactory.getGasTemperatureAbovePhysicalThresholdStart()),
    GAS_TEMP_ABOVE_PHYSICAL_THRESHOLD_END   ( 232, EndDeviceEventTypeFactory.getGasTemperatureAbovePhysicalThresholdEnd()),
    GAS_TEMP_BELOW_PHYSICAL_THRESHOLD_START ( 233, EndDeviceEventTypeFactory.getGasTemperatureBelowPhysicalThresholdStart()),
    GAS_TEMP_BELOW_PHYSICAL_THRESHOLD_END   ( 234, EndDeviceEventTypeFactory.getGasTemperatureBelowPhysicalThresholdEnd()),
    TEMP_FAILURE_START                      ( 235, EndDeviceEventTypeFactory.getTemperatureFailureStart()),
    TEMP_FAILURE_END                        ( 236, EndDeviceEventTypeFactory.getTemperatureFailureEnd()),
    PASSWORD_CHANGED                        ( 237, EndDeviceEventTypeFactory.getPasswordChanged()),
    BATTERY_LEVEL_BELOW_LOW_LEVEL_END       ( 238, EndDeviceEventTypeFactory.getBatteryLevelBelowLowLevelEnd()),
    REMOTE_COMM_FAILURE                     ( 239, EndDeviceEventTypeFactory.getRemoteCommunicationFailure()),
    PUSH_ERROR_START                        ( 240, EndDeviceEventTypeFactory.getPushErrorStart()),
    BATTERY_BELOW_CRITICAL_LEVEL            ( 241, EndDeviceEventTypeFactory.getBatteryBelowCriticalLevel()),
    FIRMWARE_UPDATE_ACTIVATION_FAILURE      ( 242, EndDeviceEventTypeFactory.getFirmwareUpdateActivationFailure()),
    PHYSICAL_MODULE_DISCONNECT              ( 243, EndDeviceEventTypeFactory.getPhysicalModuleDisconnect()),
    UNAUTHORIZED_ACCESS                     ( 244, EndDeviceEventTypeFactory.getUnauthorizedAccess()),
    DATABASE_RESET_AFTER_UPDATE             ( 245, EndDeviceEventTypeFactory.getDatabaseResetAfterUpdate()),
    POWER_LEVEL_INCREASED                   ( 246, EndDeviceEventTypeFactory.getPowerLevelIncreased()),
    POWER_LEVEL_DECREASED                   ( 247, EndDeviceEventTypeFactory.getPowerLevelDecreased()),
    POWER_LEVEL_MAXIMUM_REACHED             ( 248, EndDeviceEventTypeFactory.getPowerLevelMaximumReached()),
    POWER_LEVEL_MINIMUM_REACHED             ( 249, EndDeviceEventTypeFactory.getPowerLevelMinimumReached()),
    PM1_CHANNEL_CHANGED                     ( 250, EndDeviceEventTypeFactory.getPm1ChannelChanged()),
    PM1_ACTIVE_MODE_START                   ( 251, EndDeviceEventTypeFactory.getPm1ActiveModeStart()),
    PM1_ACTIVE_MODE_END                     ( 252, EndDeviceEventTypeFactory.getPm1ActiveModeEnd()),
    PM1_ORPHANED_MODE_START                 ( 253, EndDeviceEventTypeFactory.getPm1OrphanedModeStart()),
    PM1_ORPHANED_MODE_END                   ( 254, EndDeviceEventTypeFactory.getPm1OrphanedModeEnd()),
    PM1_PIB_UPDATED                         ( 255, EndDeviceEventTypeFactory.getPm1PibUpdated()),
    PM1_MIB_UPDATED                         ( 256, EndDeviceEventTypeFactory.getPm1MibUpdated()),
    PM1_SYNC_ACCESS_CHANGED                 ( 257, EndDeviceEventTypeFactory.getPm1SyncAccessChanged()),
    PM1_SYNC_PERIOD_CHANGED                 ( 258, EndDeviceEventTypeFactory.getPm1SyncPeriodChanged()),
    PM1_MAINTENANCE_WINDOW_CHANGED          ( 259, EndDeviceEventTypeFactory.getPm1MaintenanceWindowChanged()),
    PM1_ORPHANED_THRESHOLD_CHANGED          ( 260, EndDeviceEventTypeFactory.getPm1OrphanedThresholdChanged()),
    PM1_AFFILIATION_PARAMS_CHANGED          ( 261, EndDeviceEventTypeFactory.getPm1AffiliationParamsChanged()),
    SECONDARY_ADDRESS_RF_CHANGED            ( 262, EndDeviceEventTypeFactory.getSecondaryAddressRfChanged()),
    VALVE_PGV_CONFIGURATION_CHANGED         ( 263, EndDeviceEventTypeFactory.getValvePgvConfigurationChanged()),
    PUSH_SCHEDULER1_CHANGED                 ( 264, EndDeviceEventTypeFactory.getPushScheduler1Changed()),
    PUSH_SETUP1_CHANGED                     ( 265, EndDeviceEventTypeFactory.getPushSetup1Changed()),
    PUSH_SCHEDULER2_CHANGED                 ( 266, EndDeviceEventTypeFactory.getPushScheduler2Changed()),
    PUSH_SETUP2_CHANGED                     ( 267, EndDeviceEventTypeFactory.getPushSetup2Changed()),
    PUSH_SCHEDULER3_CHANGED                 ( 268, EndDeviceEventTypeFactory.getPushScheduler3Changed()),
    PUSH_SETUP3_CHANGED                     ( 269, EndDeviceEventTypeFactory.getPushSetup3Changed()),
    PUSH_SCHEDULER4_CHANGED                 ( 270, EndDeviceEventTypeFactory.getPushScheduler4Changed()),
    PUSH_SETUP4_CHANGED                     ( 271, EndDeviceEventTypeFactory.getPushSetup4Changed()),
    ENABLING_INSTALLER_MANTAINER            ( 272, EndDeviceEventTypeFactory.getEnablingInstallerMantainer()),
    FC_THRESHOLDS_CHANGED                   ( 273, EndDeviceEventTypeFactory.getFcThresholdsChanged()),
    REMOTE_CONNECTION_START                 ( 274, EndDeviceEventTypeFactory.getRemoteConnectionStart()),
    MAINTENANCE_WINDOW_HW_FAILURE           ( 275, EndDeviceEventTypeFactory.getMaintenanceWindowHwFailure()),
    MAINTENANCE_WINDOW_SW_FAILURE           ( 276, EndDeviceEventTypeFactory.getMaintenanceWindowSwFailure()),
    MAINTENANCE_WINDOW_START                ( 277, EndDeviceEventTypeFactory.getMaintenanceWindowStart()),
    MAINTENANCE_WINDOW_END                  ( 278, EndDeviceEventTypeFactory.getMaintenanceWindowEnd()),
    ASSOCIATION_INSTALLER_DISABLED          ( 279, EndDeviceEventTypeFactory.getAssociationInstallerDisabled()),
    VALVE_POSITION_ERROR                    ( 280, EndDeviceEventTypeFactory.getValvePositionError()),
    VALVE_ENABLE_OPENING                    ( 281, EndDeviceEventTypeFactory.getValveEnableOpening()),
    MISER_MODE_FAILURE                      ( 282, EndDeviceEventTypeFactory.getMiserModeFailure()),
    DEVICE_RESET                            ( 283, EndDeviceEventTypeFactory.getDeviceReset()),
    METROLOGIC_RESET                        ( 284, EndDeviceEventTypeFactory.getMetrologicReset()),
    ACTIVATION_NEW_TARIFF_PLAN              ( 285, EndDeviceEventTypeFactory.getActivationNewTariffPlan()),
    PLANNING_NEW_TARIFF_PLAN                ( 286, EndDeviceEventTypeFactory.getPlanningNewTariffPlan()),
    CLOCK_SYNC_FAIL                         ( 287, EndDeviceEventTypeFactory.getClockSyncFail()),
    CLOCK_SYNC                              ( 288, EndDeviceEventTypeFactory.getClockSync()),
    METROLOGICAL_PARAMETER_CONFIGURATION    ( 289, EndDeviceEventTypeFactory.getMetrologicalParameterConfiguration()),
    MEASURE_ALGORITHM_ERROR_START           ( 290, EndDeviceEventTypeFactory.getMeasureAlgorithmErrorStart()),
    MEASURE_ALGORITHM_ERROR_END             ( 291, EndDeviceEventTypeFactory.getMeasureAlgorithmErrorEnd()),
    GENERAL_ERROR_DEVICE_START              ( 292, EndDeviceEventTypeFactory.getGeneralErrorDeviceStart()),
    GENERAL_ERROR_DEVICE_END                ( 293, EndDeviceEventTypeFactory.getGeneralErrorDeviceEnd()),
    BUFFER_FULL                             ( 294, EndDeviceEventTypeFactory.getBufferFull()),
    BUFFER_ALMOST_FULL                      ( 295, EndDeviceEventTypeFactory.getBufferAlmostFull()),
    VALVE_CLOSED_BECAUSE_OF_COMMAND         ( 296, EndDeviceEventTypeFactory.getValveClosedBecauseOfCommand()),
    VALVE_OPENED                            ( 297, EndDeviceEventTypeFactory.getValveOpened()),
    MEMORY_FAILURE                          ( 298, EndDeviceEventTypeFactory.getMemoryFailure()),
    UNITS_STATUS_CHANGED                    ( 299, EndDeviceEventTypeFactory.getUniTsStatusChanged()),
    MAIN_POWER_OUTAGE_START                 ( 300, EndDeviceEventTypeFactory.getMainPowerOutageStart()),
    MAIN_POWER_OUTAGE_END                   ( 301, EndDeviceEventTypeFactory.getMainPowerOutageEnd()),
    BATTERY_LEVEL_BELOW_LOW_LEVEL_START     ( 302, EndDeviceEventTypeFactory.getBatteryLevelBelowLowLevelStart()),
    DEVICE_TAMPER_DETECTION_START           ( 303, EndDeviceEventTypeFactory.getDeviceTamperDetectionStart()),
    DEVICE_TAMPER_DETECTION_END             ( 304, EndDeviceEventTypeFactory.getDeviceTamperDetectionEnd()),
    CRITICAL_SOFTWARE_ERROR                 ( 305, EndDeviceEventTypeFactory.getCriticalSoftwareError()),
    DST_START                               ( 306, EndDeviceEventTypeFactory.getDstStart()),
    DST_END                                 ( 307, EndDeviceEventTypeFactory.getDstEnd()),
    BILLING_PERIOD_CLOSING_LOCAL_REQUEST    ( 308, EndDeviceEventTypeFactory.getBillingPeriodClosingLocalRequest()),
    BILLING_PERIOD_CLOSING_REMOTE_REQUEST   ( 309, EndDeviceEventTypeFactory.getBillingPeriodClosingRemoteRequest()),
    BATTERY_ABOVE_CRITICAL_LEVEL            ( 310, EndDeviceEventTypeFactory.getBatteryAboveCriticalLevel()),
    FIRMWARE_UPDATE_START                   ( 311, EndDeviceEventTypeFactory.getFirmwareUpdateStart()),
    FIRMWARE_UPDATE_DATE_ACTIVATION         ( 312, EndDeviceEventTypeFactory.getFirmwareUpdateDateActivation()),
    FIRMWARE_UPDATE_VERIFY_OK               ( 313, EndDeviceEventTypeFactory.getFirmwareUpdateVerifyOk()),
    FIRMWARE_UPDATE_VERIFY_FAILURE          ( 314, EndDeviceEventTypeFactory.getFirmwareUpdateVerifyFailure()),
    FIRMWARE_UPDATE_ACTIVATION_OK           ( 315, EndDeviceEventTypeFactory.getFirmwareUpdateActivationOk()),
    CLOSE_VALVE_LEAKAGE_CAUSE               ( 316, EndDeviceEventTypeFactory.getCloseValveLeakageCause()),
    CLOSE_VALVE_BATTERY_REMOVED_WITH_NO_AUTH    ( 317, EndDeviceEventTypeFactory.getCloseValveBatteryRemovedWithNoAuth()),
    CLOSE_VALVE_BATTERY_BELOW_CRITICAL_POINT    ( 318, EndDeviceEventTypeFactory.getCloseValveBatteryBelowCriticalPoint()),
    CLOSE_VALVE_MEASURE_FAILURE             ( 319, EndDeviceEventTypeFactory.getCloseValveMeasureFailure()),
    VALVE_PASSWORD_INVALID                  ( 320, EndDeviceEventTypeFactory.getValvePasswordInvalid()),
    CLOSE_VALVE_COMMUNICATION_TIMEOUT       ( 321, EndDeviceEventTypeFactory.getCloseValveCommunicationTimeout()),
    VALVE_NEW_PASSWORD                      ( 322, EndDeviceEventTypeFactory.getValveNewPassword()),
    VALVE_READY_PASSWORD_VALID              ( 323, EndDeviceEventTypeFactory.getValveReadyPasswordValid()),
    VALVE_READY_CONNECTION_OK               ( 324, EndDeviceEventTypeFactory.getValveReadyConnectionOk()),
    VALVE_RECONNECT_START                   ( 325, EndDeviceEventTypeFactory.getValveReconnectStart()),
    VALVE_RECONNECT_END                     ( 326, EndDeviceEventTypeFactory.getValveReconnectEnd()),
    VALVE_IS_CLOSED_BUT_LEAKAGE_IS_PRESENT  ( 327, EndDeviceEventTypeFactory.getValveIsClosedButLeakageIsPresent()),
    VALVE_CANNOT_OPEN_CLOSE                 ( 328, EndDeviceEventTypeFactory.getValveCannotOpenClose()),
    EXTERNAL_FIELD_APPLICATION_INTERFERING_START    ( 329, EndDeviceEventTypeFactory.getExternalFieldApplicationInterferingStart()),
    EXTERNAL_FIELD_APPLICATION_INTERFERING_END      ( 330, EndDeviceEventTypeFactory.getExternalFieldApplicationInterferingEnd()),
    ACCESS_TO_ELECTRONIC                    ( 331, EndDeviceEventTypeFactory.getAccessToElectronic()),
    UNAUTHORIZED_BATTERY_REMOVE             ( 332, EndDeviceEventTypeFactory.getUnauthorizedBatteryRemove()),
    DATABASE_RESET                          ( 333, EndDeviceEventTypeFactory.getDatabaseReset()),
    DATABASE_CORRUPTED                      ( 334, EndDeviceEventTypeFactory.getDatabaseCorrupted()),
    UPDATED_MASTERKEY                       ( 335, EndDeviceEventTypeFactory.getUpdatedMasterKey()),
    UPDATED_KEYC                            ( 336, EndDeviceEventTypeFactory.getUpdatedKeyc()),
    UPDATED_KEYT                            ( 337, EndDeviceEventTypeFactory.getUpdatedKeyt()),
    UPDATED_KEYS                            ( 338, EndDeviceEventTypeFactory.getUpdatedKeys()),
    UPDATED_KEYN                            ( 339, EndDeviceEventTypeFactory.getUpdatedKeyn()),
    UPDATED_KEYM                            ( 340, EndDeviceEventTypeFactory.getUpdatedKeym()),
    GAS_DAY_UPDATED                         ( 341, EndDeviceEventTypeFactory.getGasDayUpdated()),
    BILLING_PERIOD_UPDATED                  ( 342, EndDeviceEventTypeFactory.getBillingPeriodUpdated()),
    INSTALLER_MAINTAINER_USER_CHANGED       ( 343, EndDeviceEventTypeFactory.getInstallerMaintainerUserChanged()),
    CLOCK_PARAMETER_SCHANGED                ( 344, EndDeviceEventTypeFactory.getClockParametersChanged()),
    SYNC_ALGORITHM_CHANGED                  ( 345, EndDeviceEventTypeFactory.getSyncAlgorithmChanged()),
    PDR_CHANGED                             ( 346, EndDeviceEventTypeFactory.getPdrChanged()),
    DEFAULT_TEMPERATURE                     ( 347, EndDeviceEventTypeFactory.getDefaultTemperature()),
    FALLBACK_TEMPERATURE_CHANGED            ( 348, EndDeviceEventTypeFactory.getFallbackTemperatureChanged()),
    VALVE_CLOSE_FOR_MAX_FRAUD_ATTEMPTS      ( 349, EndDeviceEventTypeFactory.getValveCloseForMaxFraudAttempts()),
    VALVE_CLOSE_FOR_EXCEEDED_BATTERY_REMOVAL_TIME   ( 350, EndDeviceEventTypeFactory.getValveCloseForExceededBatteryRemovalTime()),
    VALVE_CONFIGURATION_PGV_BIT8_CHANGED            ( 351, EndDeviceEventTypeFactory.getValveConfigurationPgvBit8Changed()),
    TOO_HIGH_CONSUMPTION_OR_PRODUCTION      (352, EndDeviceEventTypeFactory.getHighConsumptionOrProductionEnergy()),
    INDEX_VALUE_DECREASE_OR_RESET           (353, EndDeviceEventTypeFactory.getIndexValuesDecreaseOrReset()),
    MISMATCH_BETWEEN_TOTAL_AND_TARIFF_REGISTERS(354, EndDeviceEventTypeFactory.getMismatchBetweenTotalAndTariffRegisters()),
    SEND_FRAME_COUNTER_ABOVE_THRESHOLD      (359, EndDeviceEventTypeFactory.getSendFrameCounterAboveThreshold()),
    RECEIVE_FRAME_COUNTER_ABOVE_THRESHOLD   (360, EndDeviceEventTypeFactory.getReceiveFrameCounterAboveThreshold()),
    TAMPER_BATTERY                          (355, EndDeviceEventTypeFactory.getTamperBattery() ),
    HLC_DAMAGE                              (356, EndDeviceEventTypeFactory.getHlcDamage()),
    PERMANENT_LOG_FILLED_UP_90_PERSENT      (357, EndDeviceEventTypeFactory.getPermanentLogFilledUp90Persent()),
    DEVICE_ABOUT_HIBERNATION_MODE           (358, EndDeviceEventTypeFactory.getDeviceAboutHibernationMode()),
    POWER_FAIL                              (361, EndDeviceEventTypeFactory.getPowerFail()),
    MAX_FLOW                                (362, EndDeviceEventTypeFactory.getMaxFlow()),
    TEMP_MIN_LIMIT                          (363, EndDeviceEventTypeFactory.getTempMinLimit()),
    TEMP_MAX_LIMIT                          (364, EndDeviceEventTypeFactory.getTempMaxLimit()),
    PULSE_ERROR                             (365, EndDeviceEventTypeFactory.getPulseError()),
    CONSUMPTION_ERROR                       (366, EndDeviceEventTypeFactory.getConsumptionError()),
    BATTERY_CONSUMPTION_HIGH                (367, EndDeviceEventTypeFactory.getBatteryConsumptionHigh() ),
    REVERSE_FLOW                            (368, EndDeviceEventTypeFactory.getReverseFlow() ),
    TAMPER_P2                               (369, EndDeviceEventTypeFactory.getTamperP2()),
    TAMPER_P0                               (370, EndDeviceEventTypeFactory.getTamperP0()),
    TAMPER_CASE                             (371, EndDeviceEventTypeFactory.getTamperCase()),
    SYSTEM_HW_ERROR                         (372, EndDeviceEventTypeFactory.getSystemHRError()),
    CFG_CALIBRATION_ERROR                   (373, EndDeviceEventTypeFactory.getCFGCalibrationError()),
    TEMPERATURE_SENSOR_ERROR                (374, EndDeviceEventTypeFactory.getTemperatureSensorError()),
    BINDING_FLAG                            (375, EndDeviceEventTypeFactory.getBindingFlag() ),

    EOB_RESET(376, EndDeviceEventTypeFactory.getEOBReset()),
    MANUAL_RESET(377, EndDeviceEventTypeFactory.getManualReset()),
    AUTO_RESET(378, EndDeviceEventTypeFactory.getAutoReset()),
    ROLL_OVER_TO_ZERO(379, EndDeviceEventTypeFactory.getRollOverToZero()),
    SELECTION_OF_INPUTS_SIGNALS(380, EndDeviceEventTypeFactory.getSelectionOfInputsSignals()),
    OUTPUT_RELAY_CONTROL_SIGNALS_STATE_CHANGE(381, EndDeviceEventTypeFactory.getOutputRelayControlSignalState()),
    ERROR_REGISTR_1_CHANGED(382, EndDeviceEventTypeFactory.getRegister1()),
    ERROR_REGISTR_2_CHANGED(383, EndDeviceEventTypeFactory.getRegister2()),
    ERROR_REGISTR_3_CHANGED(384, EndDeviceEventTypeFactory.getRegister3()),
    COMMUNICATION_STATUS_CHANGED(385, EndDeviceEventTypeFactory.getCommunicationStatus()),
    MAXIMUM_CURRENT(386, EndDeviceEventTypeFactory.getMaximumCurrent()),
    SAG_CONFIRMED(387, EndDeviceEventTypeFactory.getSagConfirmed()),
    SWELL_CONFIRMED(388, EndDeviceEventTypeFactory.getSwellConfirmed()),
    RECOVERY_AFTER_CURRENT_OVERLIMIT(389, EndDeviceEventTypeFactory.getRecoveryAfterCurrentOverlimit()),
    RECOVERY_TIMES_SETTING_CHANGED(390, EndDeviceEventTypeFactory.getRecoveryTimesSetting()),
    RECOVERY_MECHANISM_RELEASED(391, EndDeviceEventTypeFactory.getRecoveryMechanismReleased()),
    DISCONNECTOR_STATUS_CHANGED(392, EndDeviceEventTypeFactory.getDisconnectorStatusChanged()),
    SECURITY_EVENT(393, EndDeviceEventTypeFactory.getSecurityEvent()),
    MAXIMUM_DEMAND_EVENT(394, EndDeviceEventTypeFactory.getMaximumDemand()),

    TIME_BEFORE_CHANGE(395, EndDeviceEventTypeFactory.getTimeBeforeChangeEvent()),
    TIME_AFTER_CHANGE(396, EndDeviceEventTypeFactory.getTimeAfterChangeEvent()),
    COMM_PORT_STATUS_CHANGE(397, EndDeviceEventTypeFactory.getCommunicationStatus()),
    OUTPUT_VALVE_CONTROL(398, EndDeviceEventTypeFactory.getValveControlSignalEvent()),

    END_OF_NONPERIODIC_BILLING_INTERVAL(399, EndDeviceEventTypeFactory.getEndOfNonperiodicBillingIntervalEventType()),
    LOADPROFILE_1_CAPTURING_ENABLED(400, EndDeviceEventTypeFactory.getLoadProfile1CapturingEnabledEventType()),
    LOADPROFILE_1_CAPTURING_DISABLED(401, EndDeviceEventTypeFactory.getLoadProfile1CapturingDisabledEventType()),
    LOADPROFILE_2_CAPTURING_ENABLED(402, EndDeviceEventTypeFactory.getLoadProfile2CapturingEnabledEventType()),
    LOADPROFILE_2_CAPTURING_DISABLED(403, EndDeviceEventTypeFactory.getLoadProfile2CapturingDisabledEventType()),
    FOTA_UPGRADING_INITIATED(404, EndDeviceEventTypeFactory.getFotaUpgradingInitiatedEventType()),
    FOTA_UPGRADING_FINISH_SUCCESS(405, EndDeviceEventTypeFactory.getFotaUpgradingFinishSuccessEventType()),
    FOTA_UPGRADING_FAILED(406, EndDeviceEventTypeFactory.getFotaUpgradingFailedEventType()),
    TARIFF_SCHEME_CHANGED(407, EndDeviceEventTypeFactory.getTariffSchemeChangedEventType()),
    START_CERTIFICATION_MODE(408, EndDeviceEventTypeFactory.getStartCertificationModeEventType()),
    END_CERTIFICATION_MODE(409, EndDeviceEventTypeFactory.getEndCertificationModeEventType()),
    LOAD_MANAGEMENT_PASSIVE_CALENDAR_ACTIVATED(410, EndDeviceEventTypeFactory.getLoadManagementPassiveCalendarActivatedEventType()),
    LOAD_MANAGEMENT_ACTIVITY_CALENDAR_PROGRAMMED(411, EndDeviceEventTypeFactory.getLoadManagementActivityCalendarProgrammedEventType()),
    CONSUMER_MESSAGE_UPDATE(412, EndDeviceEventTypeFactory.getConsumerMessageUpdateEventType()),
    CONSUMER_INTERFACE_DEACTIVATED(413, EndDeviceEventTypeFactory.getConsumerInterfaceDeactivatedEventType()),
    CONSUMER_INTERFACE_REACTIVATED(414, EndDeviceEventTypeFactory.getConsumerInterfaceReactivatedEventType()),
    MODEM_REMOVED(415, EndDeviceEventTypeFactory.getModemRemovedEventType()),
    PLC_G3_PSK_CHANGE(416, EndDeviceEventTypeFactory.getPlcG3PskChangeEventType()),
    LOAD_RELAY_CHANGE_REQUEST_REMOTE(417, EndDeviceEventTypeFactory.getLoadRelayChangeRequestRemoteEventType()),
    REINITIALIZATION_RNG(418, EndDeviceEventTypeFactory.getReinitializationOfRngEventType()),
    LOCAL_INTERFACE_DEACTIVATED(419, EndDeviceEventTypeFactory.getLocalInterfaceDeactivatedEventType()),
    LOCAL_INTERFACE_REACTIVATED(420, EndDeviceEventTypeFactory.getLocalInterfaceReactivatedEventType()),
    CURRENT_REVERSAL(421, EndDeviceEventTypeFactory.getCurrentReversalEventType()),
    COMMUNICATION_STARTED_ON_REMOTE_INTERFACE_LAN_WAN(422,EndDeviceEventTypeFactory.getCommunicationStartedOnRemoteInterfaceLAN_WAN()),
    COMMUNICATION_ENDED_ON_REMOTE_INTERFACE_LAN_WAN(423, EndDeviceEventTypeFactory.getCommunicationEndedOnRemoteInterfaceLAN_WAN()),
    COMMUNICATION_STARTED_ON_LOCAL_INTERFACE_WZ(424, EndDeviceEventTypeFactory.getCommunicationStartedOnLocalInterfaceWZ()),
    COMMUNICATION_ENDED_ON_LOCAL_INTERFACE_WZ(425, EndDeviceEventTypeFactory.getCommunicationEndedOnLocalInterfaceWZ()),
    PASSIVE_ACTIVITY_CALENDAR_ACTIVATED(426, EndDeviceEventTypeFactory.getPassiveActivityCalendarActivated()),
    ACTIVITY_CALENDAR_PROGRAMMED(427, EndDeviceEventTypeFactory.getActivityCalendarProgrammed()),
    MODEM_FAILS_RESPONSE(428, EndDeviceEventTypeFactory.getModemFailsResponse()),
    SIGNAL_QUALITY_RESTORED(429, EndDeviceEventTypeFactory.getSignalQualityRestored()),
    TCP_IP_CONNECTION_ESTABLISHMENT_FAILURE( 430, EndDeviceEventTypeFactory.getTCPIPConnectionEstablishmentFailure()),
    ACK_NOT_RECEIVED( 431, EndDeviceEventTypeFactory.getAckNotReceived()),
    PING_RESPONSE_NOT_RECEIVED( 432, EndDeviceEventTypeFactory.getPingResponseNotReceived()),
    METER_RECORDS_CONTRACTOR_CHANGED_TO_ARMED_STATUS(433, EndDeviceEventTypeFactory.getMeterRecodsWhenArmedStateChanged()),
    COMMS_HUB_PRESENT(434, EndDeviceEventTypeFactory.getCommsHubPresent()),
    COMMS_HUB_REMOVED( 435, EndDeviceEventTypeFactory.getCommsHubRemoved()),
    CT_VT_RATIO_CHANGED(436, EndDeviceEventTypeFactory.getCtVtRatioChanged()),
    OVERCURRENT_L1(437, EndDeviceEventTypeFactory.getOvercurrentL1()),
    OVERCURRENT_L2(438,EndDeviceEventTypeFactory.getOvercurrentL2()),
    OVERCURRENT_L3(439, EndDeviceEventTypeFactory.getOvercurrentL3()),
    OVERCURRENT_STOPPED_L1(440, EndDeviceEventTypeFactory.getOvercurrentStoppedL1()),
    OVERCURRENT_STOPPED_L2(441, EndDeviceEventTypeFactory.getOvercurrentStoppedL2()),
    OVERCURRENT_STOPPED_L3(442, EndDeviceEventTypeFactory.getOvercurrentStoppedL3()),
    FACTOR_DEVIATION(443, EndDeviceEventTypeFactory.getFactorDeviation()),
    FACTOR_DEVIATION_END( 444, EndDeviceEventTypeFactory.getFactorDeviationEnd()),
    DECRYPTION_OR_AUTHENTICATION_FAILURE(445, EndDeviceEventTypeFactory.getDecryptionOrAuthenticationFailure()),
    SECURITY_KEYS_UPDATED(446, EndDeviceEventTypeFactory.getSecurityKeysUpdated()),
    INPUT_SIGNAL_DETECTION( 447, EndDeviceEventTypeFactory.getInputSignalDetection()),

    SOFTWARE_RESTART_REQUEST( 10001, EndDeviceEventTypeFactory.getSoftwareRestartRequest()),

    CLEARED                                 (100001, EndDeviceEventTypeFactory.getClearedEventType()),
    POWER_MANAGEMENT_SWITCH_LOW_POWER       (100002, EndDeviceEventTypeFactory.getPowerManagementSwitchLowPowerEventType()),
    POWER_MANAGEMENT_SWITCH_FULL_POWER      (100003, EndDeviceEventTypeFactory.getPowerManagementSwitchFullPowerEventType()),
    POWER_MANAGEMENT_SWITCH_REDUCED_POWER   (100004, EndDeviceEventTypeFactory.getPowerManagementSwitchReducedPowerEventType()),
    POWER_MANAGEMENT_MAINS_LOST             (100005, EndDeviceEventTypeFactory.getPowerManagementMainsLostEventType()),
    POWER_MANAGEMENT_MAINS_RECOVERED        (100006, EndDeviceEventTypeFactory.getPowerManagementMainsRecoveredEventType()),
    POWER_MANAGEMENT_LAST_GASP              (100007, EndDeviceEventTypeFactory.getPowerManagementLastGaspEventType()),
    POWER_MANAGEMENT_BATTERY_CHARGE_START   (100008, EndDeviceEventTypeFactory.getPowerManagementBatteryChargeStartEventType()),
    POWER_MANAGEMENT_BATTERY_CHARGE_STOP    (100009, EndDeviceEventTypeFactory.getPowerManagementBatteryChargeStopEventType()),
    IDIS_METER_DISCOVERY                    (100010, EndDeviceEventTypeFactory.getIdisMeterDiscoveryEventType()),
    IDIS_METER_ACCEPTED                     (100011, EndDeviceEventTypeFactory.getIdisMeterAcceptedEventType()),
    IDIS_METER_REJECTED                     (100012, EndDeviceEventTypeFactory.getIdisMeterRejectedEventType()),
    IDIS_METER_ALARM                        (100013, EndDeviceEventTypeFactory.getIdisMeterAlarmEventType()),
    IDIS_ALARM_CONDITION                    (100014, EndDeviceEventTypeFactory.getIdisAlarmConditionEventType()),
    IDIS_MULTI_MASTER                       (100015, EndDeviceEventTypeFactory.getIdisMultiMasterEventType()),
    IDIS_PLC_EQUIPMENT_IN_STATE_NEW         (100016, EndDeviceEventTypeFactory.getIdisPlcEquipmentInStateNewEventType()),
    IDIS_EXTENDED_ALARM_STATUS              (100017, EndDeviceEventTypeFactory.getIdisExtendedAlarmStatusEventType()),
    IDIS_METER_DELETED                      (100018, EndDeviceEventTypeFactory.getIdisMeterDeletedEventType()),
    IDIS_STACK_EVENT                        (100019, EndDeviceEventTypeFactory.getIdisStackEventEventType()),
    PLC_PRIME_RESTARTED                     (100020, EndDeviceEventTypeFactory.getPlcPrimeRestartedEventType()),
    PLC_PRIME_STACK_EVENT                   (100021, EndDeviceEventTypeFactory.getPlcPrimeStackEventEventType()),
    PLC_PRIME_REGISTER_NODE                 (100022, EndDeviceEventTypeFactory.getPlcPrimeRegisterNodeEventType()),
    PLC_PRIME_UNREGISTER_NODE               (100023, EndDeviceEventTypeFactory.getPlcPrimeUnregisterNodeEventType()),
    PLC_G3_RESTARTED                        (100024, EndDeviceEventTypeFactory.getPlcG3RestartedEventType()),
    PLC_G3_STACK_EVENT                      (100025, EndDeviceEventTypeFactory.getPlcG3StackEventEventType()),
    PLC_G3_REGISTER_NODE                    (100026, EndDeviceEventTypeFactory.getPlcG3RegisterNodeEventType()),
    PLC_G3_UNREGISTER_NODE                  (100027, EndDeviceEventTypeFactory.getPlcG3UnregisterNodeEventType()),
    PLC_G3_EVENT_RECEIVED                   (100028, EndDeviceEventTypeFactory.getPlcG3EventReceivedEventType()),
    PLC_G3_JOIN_REQUEST_NODE                (100029, EndDeviceEventTypeFactory.getPlcG3JoinRequestNodeEventType()),
    PLC_G3_UPPERMAC_STOPPED                 (100030, EndDeviceEventTypeFactory.getPlcG3UppermacStoppedEventType()),
    PLC_G3_UPPERMAC_STARTED                 (100031, EndDeviceEventTypeFactory.getPlcG3UppermacStartedEventType()),
    PLC_G3_JOIN_FAILED                      (100032, EndDeviceEventTypeFactory.getPlcG3JoinFailedEventType()),
    PLC_G3_AUTH_FAILURE                     (100033, EndDeviceEventTypeFactory.getPlcG3AuthFailedEventType()),
    DLMS_SERVER_SESSION_ACCEPTED            (100034, EndDeviceEventTypeFactory.getDlmsServerSessionAcceptedEventType()),
    DLMS_SERVER_SESSION_FINISHED            (100035, EndDeviceEventTypeFactory.getDlmsServerSessionFinishedEventType()),
    DLMS_OTHER                              (100036, EndDeviceEventTypeFactory.getDlmsOtherEventType()),
    DLMS_UPSTREAM_TEST                      (100037, EndDeviceEventTypeFactory.getDlmsUpstreamTestEventType()),
    MODEM_WDG_PPPD_RESET                    (100038, EndDeviceEventTypeFactory.getModemWdgPppdResetEventType()),
    MODEM_WDG_HW_RESET                      (100039, EndDeviceEventTypeFactory.getModemWdgHwResetEventType()),
    MODEM_WDG_REBOOT_REQUESTED              (100040, EndDeviceEventTypeFactory.getModemWdgRebootRequestedEventType()),
    MODEM_CONNECTED                         (100041, EndDeviceEventTypeFactory.getModemConnectedEventType()),
    MODEM_DISCONNECTED                      (100042, EndDeviceEventTypeFactory.getModemDisconnectedEventType()),
    MODEM_WAKE_UP                           (100043, EndDeviceEventTypeFactory.getModemWakeUpEventType()),
    PROTOCOL_PRELIMINARY_TASK_COMPLETED     (100044, EndDeviceEventTypeFactory.getProtocolPreliminaryTaskCompletedEventType()),
    PROTOCOL_PRELIMINARY_TASK_FAILED        (100045, EndDeviceEventTypeFactory.getProtocolPreliminaryTaskFailedEventType()),
    PROTOCOL_CONSECUTIVE_FAILURE            (100046, EndDeviceEventTypeFactory.getProtocolConsecutiveFailureEventType()),
    FIRMWARE_UPGRADE                        (100047, EndDeviceEventTypeFactory.getFirmwareUpgradeEventType()),
    FIRMWARE_MODIFIED                       (100048, EndDeviceEventTypeFactory.getFirmwareModifiedEventType()),
    CPU_OVERLOAD                            (100049, EndDeviceEventTypeFactory.getCpuOverloadEventType()),
    RAM_TOO_HIGH                            (100050, EndDeviceEventTypeFactory.getRamTooHighEventType()),
    DISK_USAGE_TOO_HIGH                     (100051, EndDeviceEventTypeFactory.getDiskUsageTooHighEventType()),
    PACE_EXCEPTION                          (100052, EndDeviceEventTypeFactory.getPaceExceptionEventType()),
    SSH_LOGIN                               (100053, EndDeviceEventTypeFactory.getSshLoginEventType()),
    FACTORY_RESET                           (100054, EndDeviceEventTypeFactory.getFactoryResetEventType()),
    WEBPORTAL_LOGIN                         (100055, EndDeviceEventTypeFactory.getWebportalLoginEventType()),
    WEBPORTAL_ACTION                        (100056, EndDeviceEventTypeFactory.getWebportalActionEventType()),
    WEBPORTAL_FAILED_LOGIN                  (100057, EndDeviceEventTypeFactory.getWebportalFailedLoginEventType()),
    WEBPORTAL_LOCKED_USER                   (100058, EndDeviceEventTypeFactory.getWebportalLockedUserEventType()),
    METER_MULTICAST_UPGRADE_START           (100059, EndDeviceEventTypeFactory.getMeterMulticastUpgradeStartEventType()),
    METER_MULTICAST_UPGRADE_COMPLETED       (100060, EndDeviceEventTypeFactory.getMeterMulticastUpgradeCompletedEventType()),
    METER_MULTICAST_UPGRADE_FAILED          (100061, EndDeviceEventTypeFactory.getMeterMulticastUpgradeFailedEventType()),
    METER_MULTICAST_UPGRADE_INFO            (100062, EndDeviceEventTypeFactory.getMeterMulticastUpgradeInfoEventType()),
    GENERAL_SECURITY_ERROR                  (100063, EndDeviceEventTypeFactory.getGeneralSecurityErrorEventType()),
    WRAP_KEY_ERROR                          (100064, EndDeviceEventTypeFactory.getWrapKeyErrorEventType()),
    DLMS_AUTHENTICATION_LEVEL_UPDATED       (100065, EndDeviceEventTypeFactory.getDlmsAuthenticationLevelUpdatedEventType()),
    DLMS_SECURITY_POLICY_UPDATED            (100066, EndDeviceEventTypeFactory.getDlmsSecurityPolicyUpdatedEventType()),
    DLMS_SECURITY_SUITE_UPDATED             (100067, EndDeviceEventTypeFactory.getDlmsSecuritySuiteUpdatedEventType()),
    DLMS_KEYS_UPDATED                       (100069, EndDeviceEventTypeFactory.getDlmsKeysUpdatedEventType()),
    DLMS_ACCESS_VIOLATION                   (100070, EndDeviceEventTypeFactory.getDlmsAccessViolationEventType()),
    DLMS_AUTHENTICATION_FAILURE             (100071, EndDeviceEventTypeFactory.getDlmsAuthenticationFailureEventType()),
    DLMS_CIPHERING_ERROR                    (100072, EndDeviceEventTypeFactory.getDlmsCipheringErrorEventType()),
    UNKNOWN_REGISTER                        (100073, EndDeviceEventTypeFactory.getUnknownRegisterEventType()),
    PLC_G3_BLACKLIST                        (100074, EndDeviceEventTypeFactory.getPlcG3BlacklistEventType()),
    PLC_G3_NODE_LINK_LOST                   (100075, EndDeviceEventTypeFactory.getPlcG3NodeLinkLostEventType()),
    PLC_G3_NODE_LINK_RECOVERED              (100076, EndDeviceEventTypeFactory.getPlcG3NodeLinkRecoveredEventType()),
    PLC_G3_PAN_ID                           (100077, EndDeviceEventTypeFactory.getPlcG3PanIdEventType()),
    PLC_G3_TOPOLOGY_UPDATE                  (100078, EndDeviceEventTypeFactory.getPlcG3TopologyUpdateEventType()),
    MODEM_NEW_SIM                           (100079, EndDeviceEventTypeFactory.getModemNewSimEventType()),
    MODEM_NEW_EQUIPMENT                     (100080, EndDeviceEventTypeFactory.getModemNewEquipmentEventType()),
    CHECK_DATA_CONCENTRATOR_CONFIG          (100081, EndDeviceEventTypeFactory.getCheckDataConcentratorConfigEventType()),
    LINK_UP                                 (100082, EndDeviceEventTypeFactory.getLinkUpEventType()),
    LINK_DOWN                               (100083, EndDeviceEventTypeFactory.getLinkDownEventType()),
    USB_ADD                                 (100084, EndDeviceEventTypeFactory.getUsbAddEventType()),
    USB_REMOVE                              (100085, EndDeviceEventTypeFactory.getUsbRemoveEventType()),
    FILE_TRANSFER_COMPLETED                 (100086, EndDeviceEventTypeFactory.getFileTransferCompletedEventType()),
    FILE_TRANSFER_FAILED                    (100087, EndDeviceEventTypeFactory.getFileTransferFailedEventType()),
    SCRIPT_EXECUTION_STARTED                (100088, EndDeviceEventTypeFactory.getScriptExecutionStartedEventType()),
    SCRIPT_EXECUTION_COMPLETED              (100089, EndDeviceEventTypeFactory.getScriptExecutionCompletedEventType()),
    SCRIPT_EXECUTION_FAILED                 (100090, EndDeviceEventTypeFactory.getScriptExecutionFailedEventType()),
    SCRIPT_EXECUTION_SCHEDULED              (100091, EndDeviceEventTypeFactory.getScriptExecutionScheduledEventType()),
    SCRIPT_EXECUTION_DESCHEDULED            (100092, EndDeviceEventTypeFactory.getScriptExecutionDescheduledEventType()),
    WEBPORTAL_CSRF_ATTACK                   (100093, EndDeviceEventTypeFactory.getWebportalCsrfAttackEventType()),
    SNMP_OTHER                              (100094, EndDeviceEventTypeFactory.getSnmpOtherEventType()),
    SNMP_INFO                               (100095, EndDeviceEventTypeFactory.getSnmpInfoEventType()),
    SNMP_UNSUPPORTED_VERSION                (100096, EndDeviceEventTypeFactory.getSnmpUnsupportedVersionEventType()),
    SNMP_UNSUPPORTED_SEC_MODEL              (100097, EndDeviceEventTypeFactory.getSnmpUnsupportedSecModelEventType()),
    SNMP_INVALID_USER_NAME                  (100098, EndDeviceEventTypeFactory.getSnmpInvalidUserNameEventType()),
    SNMP_INVALID_ENGINE_ID                  (100099, EndDeviceEventTypeFactory.getSnmpInvalidEngineIdEventType()),
    SNMP_AUTHENTICATION_FAILURE             (100100, EndDeviceEventTypeFactory.getSnmpAuthenticationFailureEventType()),
    SNMP_KEYS_UPDATED                       (100101, EndDeviceEventTypeFactory.getSnmpKeysUpdatedEventType()),
    CRL_UPDATED                             (100102, EndDeviceEventTypeFactory.getCrlUpdatedEventType()),
    CRL_UPDATE_REJECTED                     (100103, EndDeviceEventTypeFactory.getCrlUpdateRejectedEventType()),
    KEY_UPDATE_REQUEST                      (100104, EndDeviceEventTypeFactory.getKeyUpdateRequestEventType()),
    CRL_REMOVED                             (100105, EndDeviceEventTypeFactory.getCrlRemovedEventType()),
    DOT1X_SUCCESS                           (100106, EndDeviceEventTypeFactory.getDot1xSuccessEventType()),
    DOT1X_FAILURE                           (100107, EndDeviceEventTypeFactory.getDot1xFailureEventType()),
    REPLAY_ATTACK                           (100108, EndDeviceEventTypeFactory.getReplayAttackEventType()),
    CERTIFICATE_ADDED                       (100109, EndDeviceEventTypeFactory.getCertificateAddedEventType()),
    CERTIFICATE_REMOVED                     (100110, EndDeviceEventTypeFactory.getCertificateRemovedEventType()),
    CERTIFICATE_EXPIRED                     (100111, EndDeviceEventTypeFactory.getCertificateExpiredEventType()),
    POWER_DOWN_POWER_LOST                   (100112, EndDeviceEventTypeFactory.getPowerDownPowerLostEventType()),
    POWER_DOWN_USER_REQUEST                 (100113, EndDeviceEventTypeFactory.getPowerDownUserRequestEventType()),
    POWER_DOWN_SOFTWARE_FAULT               (100114, EndDeviceEventTypeFactory.getPowerDownSoftwareFaultEventType()),
    POWER_DOWN_HARDWARE_FAULT               (100115, EndDeviceEventTypeFactory.getPowerDownHardwareFaultEventType()),
    POWER_DOWN_NETWORK_INACTIVITY           (100116, EndDeviceEventTypeFactory.getPowerDownNetworkInactivityEventType()),
    POWER_DOWN_FIRMWARE_UPGRADE             (100117, EndDeviceEventTypeFactory.getPowerDownFirmwareUpgradeEventType()),
    POWER_DOWN_FIRMWARE_ROLLBACK            (100118, EndDeviceEventTypeFactory.getPowerDownFirmwareRollbackEventType()),
    POWER_DOWN_DISK_ERROR                   (100119, EndDeviceEventTypeFactory.getPowerDownDiskErrorEventType()),
    POWER_DOWN_CONFIGURATION_ERROR          (100120, EndDeviceEventTypeFactory.getPowerDownConfigurationErrorEventType()),
    POWER_DOWN_FACTORY_RESET                (100121, EndDeviceEventTypeFactory.getPowerDownFactoryResetEventType()),
    POWER_DOWN_TAMPERING                    (100122, EndDeviceEventTypeFactory.getPowerDownTamperingEventType()),
    POWER_DOWN_TEMPERATURE                  (100123, EndDeviceEventTypeFactory.getPowerDownTemperatureEventType()),
    POWER_DOWN_SYSTEM_WATCHDOG              (100124, EndDeviceEventTypeFactory.getPowerDownSystemWatchdogEventType()),
    POWER_DOWN_WWAN_MODEM_WATCHDOG          (100125, EndDeviceEventTypeFactory.getPowerDownWwanModemWatchdogEventType()),
    POWER_DOWN_SECURE_ELEMENT_WATCHDOG      (100126, EndDeviceEventTypeFactory.getPowerDownSecureElementWatchdogEventType()),
    POWER_DOWN_EXTERNAL_WATCHDOG            (100127, EndDeviceEventTypeFactory.getPowerDownExternalWatchdogEventType()),
    PROTOCOL_LOG_CLEARED                    (100128, EndDeviceEventTypeFactory.getProtocolLogClearedEventType()),
    METER_CLOCK_INVALID                     (100129, EndDeviceEventTypeFactory.getMeterClockInvalidEventType()),
    HEART_BEAT                              (100130, EndDeviceEventTypeFactory.getHeartBeatEventType()),
    CLEAR_NODE_LIST                         (100131, EndDeviceEventTypeFactory.getClearNodeListEventType());

    private final int eisCode;
    private final EndDeviceEventType eventType;

    private EndDeviceEventTypeMapping(int eisCode, EndDeviceEventType eventType) {
        this.eisCode = eisCode;
        this.eventType = eventType;
    }

    public int getEisCode() {
        return eisCode;
    }

    public EndDeviceEventType getEventType() {
        return eventType;
    }

    public static EndDeviceEventType getEventTypeCorrespondingToEISCode(int eisCode) {
        for (EndDeviceEventTypeMapping each : EndDeviceEventTypeMapping.values()) {
            if (each.getEisCode() == eisCode) {
                return each.getEventType();
            }
        }
        return OTHER.getEventType();
    }

    public static int getEISCodeCorrespondingToEventType(EndDeviceEventType endDeviceEventType) {
        for (EndDeviceEventTypeMapping each : EndDeviceEventTypeMapping.values()) {
            if (Objects.equals(each.getEventType().toString(), endDeviceEventType.toString())) {
                return each.getEisCode();
            }
        }
        return OTHER.getEisCode();
    }
}
