/*
 * Copyright (c) 2017 by Honeywell Inc. All rights reserved.
 */

package com.elster.jupiter.pki;

import org.bouncycastle.pkcs.PKCS10CertificationRequest;

import java.util.Optional;

/**
 * A renewable certificate differs in only one way from a normal certificate: It can contain a CSR
 * It might not always be possible for Connexo to generate a CSR, as the private key is required for this.
 * In the case of beacon of device certificates for example, only the beacon or device can generate a new certificate
 * (usually on request of Connexo). Nevertheless, even in the those cases, Connexo will store the CSR generated by and
 * obtained from devices/beacon for export or some other purpose.
 */
public interface RenewableCertificate extends CertificateWrapper {
    /**
     * If a CSR was created for this placeholder in order to obtain or renew a certificate, the CSR can be retrieved through this method.
     * We choose not to use the restricted class {@link sun.security.pkcs10.PKCS10} as return type for this method.
     * @return PKCS10CertificationRequest if one was generated for this placeholder.
     */
    Optional<PKCS10CertificationRequest> getCSR();

}
