/*
 * Copyright (c) 2017 by Honeywell Inc. All rights reserved.
 */

package com.elster.jupiter.pki;

import java.security.cert.CRL;
import java.util.Optional;

/**
 * Represents a trusted certificate, that is, a CA or sub-CA certificate that can be used to establish a chain of trust.
 * Being a CA certificate, a CRL can be associated with the Certificate. A private key will not be available,
 */
public interface TrustedCertificate extends CertificateWrapper {
    /**
     * If a CRL is available for this (sub)CA-certificate, it can be retrieved through this method.
     * CRL will be generated by the CA and needs to be imported into Connexo.
     * @return latest CRl, if available
     */
    Optional<CRL> getCRL(); // TODO Switch to x509CRL?

    /**
     * Sets the CRL for this CA certificate. The new CRL will be reused if
     * - The index number is lower than the current number
     * - The signature is invalid
     * - The issuer does not match the CA certificate subject
     * @param crl The updated CRL
     */
    void setCRL(CRL crl);

    TrustStore getTrustStore();
}
