CREATE INDEX IDX_EVENTTYPES ON EVENTTYPES (INSTANCEID);
CREATE INDEX IDX_NODEINSTANCELOG_PROCINSTID ON NODEINSTANCELOG(PROCESSINSTANCEID);
CREATE INDEX IDX_PROCINSTLOG_PROCINSTID ON PROCESSINSTANCELOG (PROCESSINSTANCEID);
CREATE INDEX IDX_PROCINSTLOG_STATUS ON PROCESSINSTANCELOG (STATUS);
CREATE INDEX IDX_VARINSTLOG_PROCINSTID ON VARIABLEINSTANCELOG (PROCESSINSTANCEID);
CREATE INDEX IDX_VARINSTLOG_VALUE ON VARIABLEINSTANCELOG (UPPER(VALUE));