
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src",
  "Ext.DomHelper": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/dom/Helper.js",
  "Ext.DomQuery": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/dom/Query.js",
  "Ext.EventObjectImpl": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/EventObject.js",
  "Ext.Msg": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/window/MessageBox.js",
  "Ext.Supports": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/Support.js",
  "Ext.core.DomHelper": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/dom/Helper.js",
  "Ext.core.DomQuery": "../../../../../../../../com.elster.jupiter.extjs/src/main/web/js/ext/src/dom/Query.js",
  "Ldr": "../../src",
  "Uni.override": "../../overrides"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ldr.Loader": [],
  "Ldr.model.LogLevel": [],
  "Ldr.model.Pluggable": [],
  "Ldr.model.Preference": [],
  "Ldr.model.Privilege": [],
  "Ldr.model.Translation": [],
  "Ldr.store.LogLevels": [],
  "Ldr.store.Pluggable": [],
  "Ldr.store.Preferences": [],
  "Ldr.store.Privileges": [],
  "Ldr.store.Translations": [],
  "Uni.override.form.field.ComboBox": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ldr.Loader": [],
  "Ldr.model.LogLevel": [],
  "Ldr.model.Pluggable": [],
  "Ldr.model.Preference": [],
  "Ldr.model.Privilege": [],
  "Ldr.model.Translation": [],
  "Ldr.store.LogLevels": [],
  "Ldr.store.Pluggable": [],
  "Ldr.store.Preferences": [],
  "Ldr.store.Privileges": [],
  "Ldr.store.Translations": [],
  "Uni.override.form.field.ComboBox": []
});
Ext.Loader.loadScript("../../overrides/form/field/ComboBox.js");
