package com.energyict.mdc.engine.offline.gui.selecting;

import com.energyict.mdc.engine.offline.core.TranslatorProvider;
import com.energyict.mdc.engine.offline.gui.windows.EisPropsPnl;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class MakeYourChoicePnl extends EisPropsPnl {

    private int myChoice = 0; // = canceled
    private String theQuestion = null;
    private List choices = new ArrayList(); // radio button texts
    private ButtonGroup buttonGroup = new ButtonGroup();

    /**
     * Creates new form MakeYourChoicePnl
     */
    public MakeYourChoicePnl(String question, List choices) {
        theQuestion = question;
        this.choices = choices;
        initComponents();
        initExtra();
    }

    public int getChoice() {
        return myChoice;
    }

    private void initExtra() {
        questionLabel.setText(theQuestion);
        questionLabel.setIconTextGap(15);
        questionLabel.setIcon(UIManager.getIcon("OptionPane.questionIcon"));

        boolean first = true;
        int choiceNr = 1;
        for (Iterator it = choices.iterator(); it.hasNext(); ) {
            JRadioButton rb = new JRadioButton((String) it.next());
            final int choice = choiceNr++;
            rb.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    myChoice = choice;
                }
            });
            if (first) {
                rb.setSelected(true);
                myChoice = choice;
                first = false;
            }
            buttonGroup.add(rb);
            radioButtonPanel.add(rb);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        centerPanel = new JPanel();
        mainPanel = new JPanel();
        jPanel1 = new JPanel();
        questionLabel = new JLabel();
        jPanel2 = new JPanel();
        radioButtonPanel = new JPanel();
        southPanel = new JPanel();
        buttonPanel = new JPanel();
        okButton = new JButton();
        cancelButton = new JButton();

        setLayout(new java.awt.BorderLayout());

        centerPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 5, 1)));
        jPanel1.add(questionLabel);

        mainPanel.add(jPanel1);

        radioButtonPanel.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.add(radioButtonPanel);

        mainPanel.add(jPanel2);

        centerPanel.add(mainPanel);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 6, 0));

        okButton.setText(TranslatorProvider.instance.get().getTranslator().getTranslation("ok"));
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText(TranslatorProvider.instance.get().getTranslator().getTranslation("cancel"));
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        southPanel.add(buttonPanel);

        add(southPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        performEscapeAction();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void performEscapeAction() {
        myChoice = 0; // = cancel
        doClose();
    }

    private void okButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel buttonPanel;
    private JButton cancelButton;
    private JPanel centerPanel;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel mainPanel;
    private JButton okButton;
    private JLabel questionLabel;
    private JPanel radioButtonPanel;
    private JPanel southPanel;
    // End of variables declaration//GEN-END:variables

}
