package com.energyict.dlms.cosem;

import java.io.IOException;

import com.energyict.dlms.ProtocolLink;
import com.energyict.dlms.axrdencoding.Array;
import com.energyict.dlms.axrdencoding.Integer8;
import com.energyict.dlms.axrdencoding.NullData;
import com.energyict.dlms.axrdencoding.OctetString;
import com.energyict.dlms.axrdencoding.Unsigned16;
import com.energyict.dlms.axrdencoding.Unsigned32;
import com.energyict.dlms.axrdencoding.Unsigned8;

/**
 * 
 * @author gna
 * This is an object form the bluebook 9th_v05
 * 
 * TODO object is not complete, feel free to complete the other attributes
 */
public class MBusClient extends AbstractCosemObject{
	
	private int CLASSID = 72;
	
	/** Attributes */
	private OctetString mbusPortReference = null;
	private Array captureDefinition = null;
	private Unsigned32 capturePeriod = null;
	private Unsigned8 primaryAddress = null;
	private Unsigned32 identificationNumber = null;
	private Unsigned16 manufacturereId = null;
	private Unsigned8 version = null;
	private Unsigned8 deviceType = null;
	private Unsigned8 accessNumber = null;
	private Unsigned8 status = null;
	private Unsigned8 alarm = null;
	
	/** Attribute numbers */
	static private final int ATTRB_MBUS_PORT_REFERENCE = 2;
	static private final int ATTRB_CAPTURE_DEFINITION = 3;
	static private final int ATTRB_CAPTURE_PERIOD = 4;
	static private final int ATTRB_PRIMARY_ADDRESS = 5;
	static private final int ATTRB_IDENTIFICATION_NUMBER = 6;
	static private final int ATTRB_MANUFACTURER_ID = 7;
	static private final int ATTRB_VERSION = 8;
	static private final int ATTRB_DEVICE_TYPE = 9;
	static private final int ATTRB_ACCESS_NUMBER = 10;
	static private final int ATTRB_STATUS = 11;
	static private final int ATTRB_ALARM = 12;
	
	/** Method invoke */
	static private final int METHOD_SLAVE_INSTALL = 1;
	static private final int METHOD_SLAVE_DEINSTALL = 2;
	static private final int METHOD_CAPTURE = 3;
	static private final int METHOD_RESET_ALARM = 4;
	static private final int METHOD_SYNCHRONIZE_CLOCK = 5;
	static private final int METHOD_DATA_SEND = 6;
	static private final int METHOD_SET_ENCRYPTION_KEY = 7;
	static private final int METHOD_TRANSFER_KEY = 8;
	
	public MBusClient(ProtocolLink protocolLink, ObjectReference objectReference){
		super(protocolLink, objectReference);
	}
	
	protected int getClassId(){
		return this.CLASSID;
	}
	
	/**
	 * Force to install the mbus meter with the given primaryAddress
	 * @param primaryAddress
	 * @throws IOException
	 */
	public void installSlave(int primaryAddress) throws IOException{
		invoke(METHOD_SLAVE_INSTALL, new Integer8(primaryAddress).getBEREncodedByteArray());
	}
	/**
	 * Force to deinstall the current slave meter
	 * @throws IOException
	 */
	public void deinstallSlave() throws IOException {
		invoke(METHOD_SLAVE_DEINSTALL, new Integer8(0).getBEREncodedByteArray());
	}

	/**
	 * Write the open key to the mbus device, this key is choosen by the manuf and used together with the default key
	 * of the device to generate an encrypted key(transportkey)
	 * If null is given as open key, then the encryption is disabled
	 * @param openKey
	 * @throws IOException
	 */
	public void setEncryptionKey(String openKey) throws IOException {
		if(openKey == null){
			invoke(METHOD_SET_ENCRYPTION_KEY, new NullData().getBEREncodedByteArray());
		} else {
			invoke(METHOD_SET_ENCRYPTION_KEY, OctetString.fromString(openKey).getBEREncodedByteArray());
		}
	}
	
	/**
	 * Write the encrypted key to the mbus device, this key is generated by the open key and the default key
	 * of the device
	 * @param encryptedkey
	 * @throws IOException
	 */
	public void setTransportKey(String encryptedkey) throws IOException {
		invoke(METHOD_TRANSFER_KEY, OctetString.fromString(encryptedkey).getBEREncodedByteArray());
	}
}
